# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI\main_window.ui'
#
# Created: Sat Aug  8 09:24:14 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(903, 1471)
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 903, 31))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuConnect = QtGui.QMenu(self.menubar)
        self.menuConnect.setObjectName(_fromUtf8("menuConnect"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.dock_campain = QtGui.QDockWidget(MainWindow)
        self.dock_campain.setEnabled(True)
        self.dock_campain.setFloating(False)
        self.dock_campain.setObjectName(_fromUtf8("dock_campain"))
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.gridLayout_2 = QtGui.QGridLayout(self.dockWidgetContents)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.create_campain_tabs = QtGui.QTabWidget(self.dockWidgetContents)
        self.create_campain_tabs.setObjectName(_fromUtf8("create_campain_tabs"))
        self.map_designer_tab = QtGui.QWidget()
        self.map_designer_tab.setObjectName(_fromUtf8("map_designer_tab"))
        self.gridLayout_6 = QtGui.QGridLayout(self.map_designer_tab)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.groubox_toolbox = QtGui.QGroupBox(self.map_designer_tab)
        self.groubox_toolbox.setFocusPolicy(QtCore.Qt.TabFocus)
        self.groubox_toolbox.setObjectName(_fromUtf8("groubox_toolbox"))
        self.gridLayout_9 = QtGui.QGridLayout(self.groubox_toolbox)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.toolbox_tabs = QtGui.QTabWidget(self.groubox_toolbox)
        self.toolbox_tabs.setTabPosition(QtGui.QTabWidget.East)
        self.toolbox_tabs.setObjectName(_fromUtf8("toolbox_tabs"))
        self.door_tab = QtGui.QWidget()
        self.door_tab.setObjectName(_fromUtf8("door_tab"))
        self.gridLayout_8 = QtGui.QGridLayout(self.door_tab)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.tool_door_secret = QtGui.QRadioButton(self.door_tab)
        self.tool_door_secret.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/images/tiles/squared_tileset/door/door_secret.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tool_door_secret.setIcon(icon)
        self.tool_door_secret.setIconSize(QtCore.QSize(64, 64))
        self.tool_door_secret.setObjectName(_fromUtf8("tool_door_secret"))
        self.gridLayout_8.addWidget(self.tool_door_secret, 1, 1, 1, 1)
        self.tool_door_double = QtGui.QRadioButton(self.door_tab)
        self.tool_door_double.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/images/tiles/squared_tileset/door/door_double.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tool_door_double.setIcon(icon1)
        self.tool_door_double.setIconSize(QtCore.QSize(64, 64))
        self.tool_door_double.setObjectName(_fromUtf8("tool_door_double"))
        self.gridLayout_8.addWidget(self.tool_door_double, 0, 1, 1, 1)
        self.tool_door_concealed = QtGui.QRadioButton(self.door_tab)
        self.tool_door_concealed.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/images/tiles/squared_tileset/door/door_concealed.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tool_door_concealed.setIcon(icon2)
        self.tool_door_concealed.setIconSize(QtCore.QSize(64, 64))
        self.tool_door_concealed.setObjectName(_fromUtf8("tool_door_concealed"))
        self.gridLayout_8.addWidget(self.tool_door_concealed, 3, 1, 1, 1)
        self.tool_door_fake = QtGui.QRadioButton(self.door_tab)
        self.tool_door_fake.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/images/tiles/squared_tileset/door/door_fake.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tool_door_fake.setIcon(icon3)
        self.tool_door_fake.setIconSize(QtCore.QSize(64, 64))
        self.tool_door_fake.setObjectName(_fromUtf8("tool_door_fake"))
        self.gridLayout_8.addWidget(self.tool_door_fake, 2, 0, 1, 1)
        self.tool_door_oneway = QtGui.QRadioButton(self.door_tab)
        self.tool_door_oneway.setText(_fromUtf8(""))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/images/tiles/squared_tileset/door/door_oneway.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tool_door_oneway.setIcon(icon4)
        self.tool_door_oneway.setIconSize(QtCore.QSize(64, 64))
        self.tool_door_oneway.setObjectName(_fromUtf8("tool_door_oneway"))
        self.gridLayout_8.addWidget(self.tool_door_oneway, 2, 1, 1, 1)
        self.tool_door_simple = QtGui.QRadioButton(self.door_tab)
        self.tool_door_simple.setText(_fromUtf8(""))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/images/tiles/squared_tileset/door/door_simple.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tool_door_simple.setIcon(icon5)
        self.tool_door_simple.setIconSize(QtCore.QSize(64, 64))
        self.tool_door_simple.setChecked(True)
        self.tool_door_simple.setObjectName(_fromUtf8("tool_door_simple"))
        self.gridLayout_8.addWidget(self.tool_door_simple, 0, 0, 1, 1)
        self.tool_door_open = QtGui.QRadioButton(self.door_tab)
        self.tool_door_open.setText(_fromUtf8(""))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/images/tiles/squared_tileset/door/door_open.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tool_door_open.setIcon(icon6)
        self.tool_door_open.setIconSize(QtCore.QSize(64, 64))
        self.tool_door_open.setObjectName(_fromUtf8("tool_door_open"))
        self.gridLayout_8.addWidget(self.tool_door_open, 1, 0, 1, 1)
        self.tool_door_rotating = QtGui.QRadioButton(self.door_tab)
        self.tool_door_rotating.setText(_fromUtf8(""))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/images/tiles/squared_tileset/door/door_rotating.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tool_door_rotating.setIcon(icon7)
        self.tool_door_rotating.setIconSize(QtCore.QSize(64, 64))
        self.tool_door_rotating.setObjectName(_fromUtf8("tool_door_rotating"))
        self.gridLayout_8.addWidget(self.tool_door_rotating, 3, 0, 1, 1)
        self.tool_door_secretoneway = QtGui.QRadioButton(self.door_tab)
        self.tool_door_secretoneway.setText(_fromUtf8(""))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/images/tiles/squared_tileset/door/door_secretoneway.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tool_door_secretoneway.setIcon(icon8)
        self.tool_door_secretoneway.setIconSize(QtCore.QSize(64, 64))
        self.tool_door_secretoneway.setObjectName(_fromUtf8("tool_door_secretoneway"))
        self.gridLayout_8.addWidget(self.tool_door_secretoneway, 4, 0, 1, 1)
        self.toolbox_tabs.addTab(self.door_tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.toolbox_tabs.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.toolbox_tabs.addTab(self.tab_3, _fromUtf8(""))
        self.gridLayout_9.addWidget(self.toolbox_tabs, 3, 0, 1, 1)
        self.layout_type_graph_paper = QtGui.QHBoxLayout()
        self.layout_type_graph_paper.setObjectName(_fromUtf8("layout_type_graph_paper"))
        self.toolbox_radio_paper_empty = QtGui.QRadioButton(self.groubox_toolbox)
        self.toolbox_radio_paper_empty.setObjectName(_fromUtf8("toolbox_radio_paper_empty"))
        self.buttonGroup = QtGui.QButtonGroup(MainWindow)
        self.buttonGroup.setObjectName(_fromUtf8("buttonGroup"))
        self.buttonGroup.addButton(self.toolbox_radio_paper_empty)
        self.layout_type_graph_paper.addWidget(self.toolbox_radio_paper_empty)
        self.toolbox_radio_paper_square = QtGui.QRadioButton(self.groubox_toolbox)
        self.toolbox_radio_paper_square.setFocusPolicy(QtCore.Qt.NoFocus)
        self.toolbox_radio_paper_square.setChecked(True)
        self.toolbox_radio_paper_square.setObjectName(_fromUtf8("toolbox_radio_paper_square"))
        self.buttonGroup.addButton(self.toolbox_radio_paper_square)
        self.layout_type_graph_paper.addWidget(self.toolbox_radio_paper_square)
        self.toolbox_radio_paper_hexagonal = QtGui.QRadioButton(self.groubox_toolbox)
        self.toolbox_radio_paper_hexagonal.setObjectName(_fromUtf8("toolbox_radio_paper_hexagonal"))
        self.buttonGroup.addButton(self.toolbox_radio_paper_hexagonal)
        self.layout_type_graph_paper.addWidget(self.toolbox_radio_paper_hexagonal)
        self.gridLayout_9.addLayout(self.layout_type_graph_paper, 0, 0, 1, 1)
        self.gridLayout_6.addWidget(self.groubox_toolbox, 0, 1, 1, 1)
        self.graphicsView = QtGui.QGraphicsView(self.map_designer_tab)
        self.graphicsView.setObjectName(_fromUtf8("graphicsView"))
        self.gridLayout_6.addWidget(self.graphicsView, 0, 0, 1, 1)
        self.create_campain_tabs.addTab(self.map_designer_tab, _fromUtf8(""))
        self.random_encounters_tab = QtGui.QWidget()
        self.random_encounters_tab.setObjectName(_fromUtf8("random_encounters_tab"))
        self.gridLayout_3 = QtGui.QGridLayout(self.random_encounters_tab)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_environmentofencounter = QtGui.QLabel(self.random_encounters_tab)
        self.label_environmentofencounter.setObjectName(_fromUtf8("label_environmentofencounter"))
        self.gridLayout_3.addWidget(self.label_environmentofencounter, 0, 0, 1, 1)
        self.group_generatedtable = QtGui.QGroupBox(self.random_encounters_tab)
        self.group_generatedtable.setObjectName(_fromUtf8("group_generatedtable"))
        self.gridLayout_4 = QtGui.QGridLayout(self.group_generatedtable)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.layout_generatedtable = QtGui.QFormLayout()
        self.layout_generatedtable.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.layout_generatedtable.setObjectName(_fromUtf8("layout_generatedtable"))
        self.label_generatedtable_1 = QtGui.QLabel(self.group_generatedtable)
        self.label_generatedtable_1.setObjectName(_fromUtf8("label_generatedtable_1"))
        self.layout_generatedtable.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_generatedtable_1)
        self.label_nameofrolledmonster_1 = QtGui.QLabel(self.group_generatedtable)
        self.label_nameofrolledmonster_1.setObjectName(_fromUtf8("label_nameofrolledmonster_1"))
        self.layout_generatedtable.setWidget(0, QtGui.QFormLayout.FieldRole, self.label_nameofrolledmonster_1)
        self.label_generatedtable_2 = QtGui.QLabel(self.group_generatedtable)
        self.label_generatedtable_2.setObjectName(_fromUtf8("label_generatedtable_2"))
        self.layout_generatedtable.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_generatedtable_2)
        self.label_nameofrolledmonster_2 = QtGui.QLabel(self.group_generatedtable)
        self.label_nameofrolledmonster_2.setObjectName(_fromUtf8("label_nameofrolledmonster_2"))
        self.layout_generatedtable.setWidget(1, QtGui.QFormLayout.FieldRole, self.label_nameofrolledmonster_2)
        self.label_generatedtable_3 = QtGui.QLabel(self.group_generatedtable)
        self.label_generatedtable_3.setObjectName(_fromUtf8("label_generatedtable_3"))
        self.layout_generatedtable.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_generatedtable_3)
        self.label_nameofrolledmonster_3 = QtGui.QLabel(self.group_generatedtable)
        self.label_nameofrolledmonster_3.setObjectName(_fromUtf8("label_nameofrolledmonster_3"))
        self.layout_generatedtable.setWidget(2, QtGui.QFormLayout.FieldRole, self.label_nameofrolledmonster_3)
        self.label_generatedtable_4 = QtGui.QLabel(self.group_generatedtable)
        self.label_generatedtable_4.setObjectName(_fromUtf8("label_generatedtable_4"))
        self.layout_generatedtable.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_generatedtable_4)
        self.label_nameofrolledmonster_4 = QtGui.QLabel(self.group_generatedtable)
        self.label_nameofrolledmonster_4.setObjectName(_fromUtf8("label_nameofrolledmonster_4"))
        self.layout_generatedtable.setWidget(3, QtGui.QFormLayout.FieldRole, self.label_nameofrolledmonster_4)
        self.label_generatedtable_5 = QtGui.QLabel(self.group_generatedtable)
        self.label_generatedtable_5.setObjectName(_fromUtf8("label_generatedtable_5"))
        self.layout_generatedtable.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_generatedtable_5)
        self.label_nameofrolledmonster_5 = QtGui.QLabel(self.group_generatedtable)
        self.label_nameofrolledmonster_5.setObjectName(_fromUtf8("label_nameofrolledmonster_5"))
        self.layout_generatedtable.setWidget(4, QtGui.QFormLayout.FieldRole, self.label_nameofrolledmonster_5)
        self.label_generatedtable_6 = QtGui.QLabel(self.group_generatedtable)
        self.label_generatedtable_6.setObjectName(_fromUtf8("label_generatedtable_6"))
        self.layout_generatedtable.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_generatedtable_6)
        self.label_nameofrolledmonster_6 = QtGui.QLabel(self.group_generatedtable)
        self.label_nameofrolledmonster_6.setObjectName(_fromUtf8("label_nameofrolledmonster_6"))
        self.layout_generatedtable.setWidget(5, QtGui.QFormLayout.FieldRole, self.label_nameofrolledmonster_6)
        self.label_generatedtable_7 = QtGui.QLabel(self.group_generatedtable)
        self.label_generatedtable_7.setObjectName(_fromUtf8("label_generatedtable_7"))
        self.layout_generatedtable.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_generatedtable_7)
        self.label_nameofrolledmonster_7 = QtGui.QLabel(self.group_generatedtable)
        self.label_nameofrolledmonster_7.setObjectName(_fromUtf8("label_nameofrolledmonster_7"))
        self.layout_generatedtable.setWidget(6, QtGui.QFormLayout.FieldRole, self.label_nameofrolledmonster_7)
        self.label_generatedtable_8 = QtGui.QLabel(self.group_generatedtable)
        self.label_generatedtable_8.setObjectName(_fromUtf8("label_generatedtable_8"))
        self.layout_generatedtable.setWidget(7, QtGui.QFormLayout.LabelRole, self.label_generatedtable_8)
        self.label_nameofrolledmonster_8 = QtGui.QLabel(self.group_generatedtable)
        self.label_nameofrolledmonster_8.setObjectName(_fromUtf8("label_nameofrolledmonster_8"))
        self.layout_generatedtable.setWidget(7, QtGui.QFormLayout.FieldRole, self.label_nameofrolledmonster_8)
        self.label_generatedtable_9 = QtGui.QLabel(self.group_generatedtable)
        self.label_generatedtable_9.setObjectName(_fromUtf8("label_generatedtable_9"))
        self.layout_generatedtable.setWidget(8, QtGui.QFormLayout.LabelRole, self.label_generatedtable_9)
        self.label_nameofrolledmonster_9 = QtGui.QLabel(self.group_generatedtable)
        self.label_nameofrolledmonster_9.setObjectName(_fromUtf8("label_nameofrolledmonster_9"))
        self.layout_generatedtable.setWidget(8, QtGui.QFormLayout.FieldRole, self.label_nameofrolledmonster_9)
        self.label_generatedtable_10 = QtGui.QLabel(self.group_generatedtable)
        self.label_generatedtable_10.setObjectName(_fromUtf8("label_generatedtable_10"))
        self.layout_generatedtable.setWidget(9, QtGui.QFormLayout.LabelRole, self.label_generatedtable_10)
        self.label_nameofrolledmonster_10 = QtGui.QLabel(self.group_generatedtable)
        self.label_nameofrolledmonster_10.setObjectName(_fromUtf8("label_nameofrolledmonster_10"))
        self.layout_generatedtable.setWidget(9, QtGui.QFormLayout.FieldRole, self.label_nameofrolledmonster_10)
        self.label_generatedtable_11 = QtGui.QLabel(self.group_generatedtable)
        self.label_generatedtable_11.setObjectName(_fromUtf8("label_generatedtable_11"))
        self.layout_generatedtable.setWidget(10, QtGui.QFormLayout.LabelRole, self.label_generatedtable_11)
        self.label_nameofrolledmonster_11 = QtGui.QLabel(self.group_generatedtable)
        self.label_nameofrolledmonster_11.setObjectName(_fromUtf8("label_nameofrolledmonster_11"))
        self.layout_generatedtable.setWidget(10, QtGui.QFormLayout.FieldRole, self.label_nameofrolledmonster_11)
        self.label_generatedtable_12 = QtGui.QLabel(self.group_generatedtable)
        self.label_generatedtable_12.setObjectName(_fromUtf8("label_generatedtable_12"))
        self.layout_generatedtable.setWidget(11, QtGui.QFormLayout.LabelRole, self.label_generatedtable_12)
        self.label_nameofrolledmonster_12 = QtGui.QLabel(self.group_generatedtable)
        self.label_nameofrolledmonster_12.setObjectName(_fromUtf8("label_nameofrolledmonster_12"))
        self.layout_generatedtable.setWidget(11, QtGui.QFormLayout.FieldRole, self.label_nameofrolledmonster_12)
        self.button_rollamonster = QtGui.QPushButton(self.group_generatedtable)
        self.button_rollamonster.setObjectName(_fromUtf8("button_rollamonster"))
        self.layout_generatedtable.setWidget(12, QtGui.QFormLayout.LabelRole, self.button_rollamonster)
        self.button_rollatable = QtGui.QPushButton(self.group_generatedtable)
        self.button_rollatable.setObjectName(_fromUtf8("button_rollatable"))
        self.layout_generatedtable.setWidget(12, QtGui.QFormLayout.FieldRole, self.button_rollatable)
        self.gridLayout_4.addLayout(self.layout_generatedtable, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.group_generatedtable, 4, 0, 3, 1)
        self.group_statsofrolledmonster = QtGui.QGroupBox(self.random_encounters_tab)
        self.group_statsofrolledmonster.setObjectName(_fromUtf8("group_statsofrolledmonster"))
        self.gridLayout_10 = QtGui.QGridLayout(self.group_statsofrolledmonster)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.label_statsofrolledmonster_treasurevalue = QtGui.QLabel(self.group_statsofrolledmonster)
        self.label_statsofrolledmonster_treasurevalue.setObjectName(_fromUtf8("label_statsofrolledmonster_treasurevalue"))
        self.gridLayout_10.addWidget(self.label_statsofrolledmonster_treasurevalue, 7, 0, 1, 1)
        self.monster_xp_value = QtGui.QLabel(self.group_statsofrolledmonster)
        self.monster_xp_value.setObjectName(_fromUtf8("monster_xp_value"))
        self.gridLayout_10.addWidget(self.monster_xp_value, 9, 1, 1, 1)
        self.label_statsofrolledmonster_hp = QtGui.QLabel(self.group_statsofrolledmonster)
        self.label_statsofrolledmonster_hp.setObjectName(_fromUtf8("label_statsofrolledmonster_hp"))
        self.gridLayout_10.addWidget(self.label_statsofrolledmonster_hp, 0, 0, 1, 1)
        self.monster_ac_value = QtGui.QLabel(self.group_statsofrolledmonster)
        self.monster_ac_value.setObjectName(_fromUtf8("monster_ac_value"))
        self.gridLayout_10.addWidget(self.monster_ac_value, 1, 1, 1, 1)
        self.label_statsofrolledmonster_xpvalue = QtGui.QLabel(self.group_statsofrolledmonster)
        self.label_statsofrolledmonster_xpvalue.setObjectName(_fromUtf8("label_statsofrolledmonster_xpvalue"))
        self.gridLayout_10.addWidget(self.label_statsofrolledmonster_xpvalue, 9, 0, 1, 1)
        self.monster_alignment_value = QtGui.QLabel(self.group_statsofrolledmonster)
        self.monster_alignment_value.setObjectName(_fromUtf8("monster_alignment_value"))
        self.gridLayout_10.addWidget(self.monster_alignment_value, 8, 1, 1, 1)
        self.label_statsofrolledmonster_ac = QtGui.QLabel(self.group_statsofrolledmonster)
        self.label_statsofrolledmonster_ac.setObjectName(_fromUtf8("label_statsofrolledmonster_ac"))
        self.gridLayout_10.addWidget(self.label_statsofrolledmonster_ac, 1, 0, 1, 1)
        self.monster_moral_value = QtGui.QLabel(self.group_statsofrolledmonster)
        self.monster_moral_value.setObjectName(_fromUtf8("monster_moral_value"))
        self.gridLayout_10.addWidget(self.monster_moral_value, 5, 1, 1, 1)
        self.monster_attack_value = QtGui.QLabel(self.group_statsofrolledmonster)
        self.monster_attack_value.setObjectName(_fromUtf8("monster_attack_value"))
        self.gridLayout_10.addWidget(self.monster_attack_value, 3, 1, 1, 1)
        self.label_statsofrolledmonster_moral = QtGui.QLabel(self.group_statsofrolledmonster)
        self.label_statsofrolledmonster_moral.setObjectName(_fromUtf8("label_statsofrolledmonster_moral"))
        self.gridLayout_10.addWidget(self.label_statsofrolledmonster_moral, 5, 0, 1, 1)
        self.label_statsofrolledmonster_attacks = QtGui.QLabel(self.group_statsofrolledmonster)
        self.label_statsofrolledmonster_attacks.setObjectName(_fromUtf8("label_statsofrolledmonster_attacks"))
        self.gridLayout_10.addWidget(self.label_statsofrolledmonster_attacks, 3, 0, 1, 1)
        self.monster_movement_value = QtGui.QLabel(self.group_statsofrolledmonster)
        self.monster_movement_value.setObjectName(_fromUtf8("monster_movement_value"))
        self.gridLayout_10.addWidget(self.monster_movement_value, 2, 1, 1, 1)
        self.label_statsofrolledmonster_movement = QtGui.QLabel(self.group_statsofrolledmonster)
        self.label_statsofrolledmonster_movement.setObjectName(_fromUtf8("label_statsofrolledmonster_movement"))
        self.gridLayout_10.addWidget(self.label_statsofrolledmonster_movement, 2, 0, 1, 1)
        self.label_statsofrolledmonster_alignment = QtGui.QLabel(self.group_statsofrolledmonster)
        self.label_statsofrolledmonster_alignment.setObjectName(_fromUtf8("label_statsofrolledmonster_alignment"))
        self.gridLayout_10.addWidget(self.label_statsofrolledmonster_alignment, 8, 0, 1, 1)
        self.monster_damages_value = QtGui.QLabel(self.group_statsofrolledmonster)
        self.monster_damages_value.setObjectName(_fromUtf8("monster_damages_value"))
        self.gridLayout_10.addWidget(self.monster_damages_value, 4, 1, 1, 1)
        self.label_statsofrolledmonster_damages = QtGui.QLabel(self.group_statsofrolledmonster)
        self.label_statsofrolledmonster_damages.setObjectName(_fromUtf8("label_statsofrolledmonster_damages"))
        self.gridLayout_10.addWidget(self.label_statsofrolledmonster_damages, 4, 0, 1, 1)
        self.label_statsofrolledmonster_saves = QtGui.QLabel(self.group_statsofrolledmonster)
        self.label_statsofrolledmonster_saves.setObjectName(_fromUtf8("label_statsofrolledmonster_saves"))
        self.gridLayout_10.addWidget(self.label_statsofrolledmonster_saves, 6, 0, 1, 1)
        self.layout_savesomonster = QtGui.QGridLayout()
        self.layout_savesomonster.setObjectName(_fromUtf8("layout_savesomonster"))
        self.monster_saves_poison_value = QtGui.QLabel(self.group_statsofrolledmonster)
        self.monster_saves_poison_value.setObjectName(_fromUtf8("monster_saves_poison_value"))
        self.layout_savesomonster.addWidget(self.monster_saves_poison_value, 1, 0, 1, 1)
        self.label_monster_saves_poi = QtGui.QLabel(self.group_statsofrolledmonster)
        self.label_monster_saves_poi.setObjectName(_fromUtf8("label_monster_saves_poi"))
        self.layout_savesomonster.addWidget(self.label_monster_saves_poi, 0, 0, 1, 1)
        self.label_monster_saves_dra = QtGui.QLabel(self.group_statsofrolledmonster)
        self.label_monster_saves_dra.setObjectName(_fromUtf8("label_monster_saves_dra"))
        self.layout_savesomonster.addWidget(self.label_monster_saves_dra, 0, 3, 1, 1)
        self.label_monster_saves_par = QtGui.QLabel(self.group_statsofrolledmonster)
        self.label_monster_saves_par.setObjectName(_fromUtf8("label_monster_saves_par"))
        self.layout_savesomonster.addWidget(self.label_monster_saves_par, 0, 2, 1, 1)
        self.label_monster_saves_wan = QtGui.QLabel(self.group_statsofrolledmonster)
        self.label_monster_saves_wan.setObjectName(_fromUtf8("label_monster_saves_wan"))
        self.layout_savesomonster.addWidget(self.label_monster_saves_wan, 0, 1, 1, 1)
        self.label_monster_saves_spe = QtGui.QLabel(self.group_statsofrolledmonster)
        self.label_monster_saves_spe.setObjectName(_fromUtf8("label_monster_saves_spe"))
        self.layout_savesomonster.addWidget(self.label_monster_saves_spe, 0, 4, 1, 1)
        self.monster_saves_wands_value = QtGui.QLabel(self.group_statsofrolledmonster)
        self.monster_saves_wands_value.setObjectName(_fromUtf8("monster_saves_wands_value"))
        self.layout_savesomonster.addWidget(self.monster_saves_wands_value, 1, 1, 1, 1)
        self.monster_saves_paralysis_value = QtGui.QLabel(self.group_statsofrolledmonster)
        self.monster_saves_paralysis_value.setObjectName(_fromUtf8("monster_saves_paralysis_value"))
        self.layout_savesomonster.addWidget(self.monster_saves_paralysis_value, 1, 2, 1, 1)
        self.monster_saves_dragonbreath_value = QtGui.QLabel(self.group_statsofrolledmonster)
        self.monster_saves_dragonbreath_value.setObjectName(_fromUtf8("monster_saves_dragonbreath_value"))
        self.layout_savesomonster.addWidget(self.monster_saves_dragonbreath_value, 1, 3, 1, 1)
        self.monster_saves_spells_value = QtGui.QLabel(self.group_statsofrolledmonster)
        self.monster_saves_spells_value.setObjectName(_fromUtf8("monster_saves_spells_value"))
        self.layout_savesomonster.addWidget(self.monster_saves_spells_value, 1, 4, 1, 1)
        self.gridLayout_10.addLayout(self.layout_savesomonster, 6, 1, 1, 1)
        self.layout_hpofmonster = QtGui.QHBoxLayout()
        self.layout_hpofmonster.setObjectName(_fromUtf8("layout_hpofmonster"))
        self.progressbar_healthorolledmonster = QtGui.QProgressBar(self.group_statsofrolledmonster)
        self.progressbar_healthorolledmonster.setProperty("value", 100)
        self.progressbar_healthorolledmonster.setObjectName(_fromUtf8("progressbar_healthorolledmonster"))
        self.layout_hpofmonster.addWidget(self.progressbar_healthorolledmonster)
        self.spin_damagetoinflict = QtGui.QSpinBox(self.group_statsofrolledmonster)
        self.spin_damagetoinflict.setObjectName(_fromUtf8("spin_damagetoinflict"))
        self.layout_hpofmonster.addWidget(self.spin_damagetoinflict)
        self.button_inflictdamage = QtGui.QPushButton(self.group_statsofrolledmonster)
        self.button_inflictdamage.setObjectName(_fromUtf8("button_inflictdamage"))
        self.layout_hpofmonster.addWidget(self.button_inflictdamage)
        self.gridLayout_10.addLayout(self.layout_hpofmonster, 0, 1, 1, 1)
        self.monster_treasure_value = QtGui.QLabel(self.group_statsofrolledmonster)
        self.monster_treasure_value.setObjectName(_fromUtf8("monster_treasure_value"))
        self.gridLayout_10.addWidget(self.monster_treasure_value, 7, 1, 1, 1)
        self.gridLayout_3.addWidget(self.group_statsofrolledmonster, 4, 1, 3, 1)
        self.combo_environmentofencounter = QtGui.QComboBox(self.random_encounters_tab)
        self.combo_environmentofencounter.setObjectName(_fromUtf8("combo_environmentofencounter"))
        self.combo_environmentofencounter.addItem(_fromUtf8(""))
        self.combo_environmentofencounter.addItem(_fromUtf8(""))
        self.combo_environmentofencounter.addItem(_fromUtf8(""))
        self.combo_environmentofencounter.addItem(_fromUtf8(""))
        self.combo_environmentofencounter.addItem(_fromUtf8(""))
        self.combo_environmentofencounter.addItem(_fromUtf8(""))
        self.combo_environmentofencounter.addItem(_fromUtf8(""))
        self.combo_environmentofencounter.addItem(_fromUtf8(""))
        self.combo_environmentofencounter.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.combo_environmentofencounter, 0, 1, 1, 1)
        self.label_chanceofencounter = QtGui.QLabel(self.random_encounters_tab)
        self.label_chanceofencounter.setObjectName(_fromUtf8("label_chanceofencounter"))
        self.gridLayout_3.addWidget(self.label_chanceofencounter, 2, 0, 1, 1)
        self.layout_horiz_chancofencounter = QtGui.QHBoxLayout()
        self.layout_horiz_chancofencounter.setObjectName(_fromUtf8("layout_horiz_chancofencounter"))
        self.slider_chanceofencounter = QtGui.QSlider(self.random_encounters_tab)
        self.slider_chanceofencounter.setMaximum(100)
        self.slider_chanceofencounter.setProperty("value", 10)
        self.slider_chanceofencounter.setOrientation(QtCore.Qt.Horizontal)
        self.slider_chanceofencounter.setObjectName(_fromUtf8("slider_chanceofencounter"))
        self.layout_horiz_chancofencounter.addWidget(self.slider_chanceofencounter)
        self.label_display_chanceofencounter = QtGui.QLabel(self.random_encounters_tab)
        self.label_display_chanceofencounter.setObjectName(_fromUtf8("label_display_chanceofencounter"))
        self.layout_horiz_chancofencounter.addWidget(self.label_display_chanceofencounter)
        self.gridLayout_3.addLayout(self.layout_horiz_chancofencounter, 2, 1, 1, 1)
        self.create_campain_tabs.addTab(self.random_encounters_tab, _fromUtf8(""))
        self.treasure_generator_tab = QtGui.QWidget()
        self.treasure_generator_tab.setObjectName(_fromUtf8("treasure_generator_tab"))
        self.gridLayout_14 = QtGui.QGridLayout(self.treasure_generator_tab)
        self.gridLayout_14.setObjectName(_fromUtf8("gridLayout_14"))
        self.widget_7 = QtGui.QWidget(self.treasure_generator_tab)
        self.widget_7.setObjectName(_fromUtf8("widget_7"))
        self.gridLayout_15 = QtGui.QGridLayout(self.widget_7)
        self.gridLayout_15.setMargin(0)
        self.gridLayout_15.setObjectName(_fromUtf8("gridLayout_15"))
        self.combobox_treasure_type = QtGui.QComboBox(self.widget_7)
        self.combobox_treasure_type.setObjectName(_fromUtf8("combobox_treasure_type"))
        self.combobox_treasure_type.addItem(_fromUtf8(""))
        self.combobox_treasure_type.addItem(_fromUtf8(""))
        self.combobox_treasure_type.addItem(_fromUtf8(""))
        self.combobox_treasure_type.addItem(_fromUtf8(""))
        self.combobox_treasure_type.addItem(_fromUtf8(""))
        self.combobox_treasure_type.addItem(_fromUtf8(""))
        self.combobox_treasure_type.addItem(_fromUtf8(""))
        self.combobox_treasure_type.addItem(_fromUtf8(""))
        self.combobox_treasure_type.addItem(_fromUtf8(""))
        self.combobox_treasure_type.addItem(_fromUtf8(""))
        self.combobox_treasure_type.addItem(_fromUtf8(""))
        self.combobox_treasure_type.addItem(_fromUtf8(""))
        self.combobox_treasure_type.addItem(_fromUtf8(""))
        self.combobox_treasure_type.addItem(_fromUtf8(""))
        self.combobox_treasure_type.addItem(_fromUtf8(""))
        self.combobox_treasure_type.addItem(_fromUtf8(""))
        self.combobox_treasure_type.addItem(_fromUtf8(""))
        self.combobox_treasure_type.addItem(_fromUtf8(""))
        self.combobox_treasure_type.addItem(_fromUtf8(""))
        self.combobox_treasure_type.addItem(_fromUtf8(""))
        self.combobox_treasure_type.addItem(_fromUtf8(""))
        self.combobox_treasure_type.addItem(_fromUtf8(""))
        self.gridLayout_15.addWidget(self.combobox_treasure_type, 0, 1, 1, 1)
        self.label_treasure_type = QtGui.QLabel(self.widget_7)
        self.label_treasure_type.setObjectName(_fromUtf8("label_treasure_type"))
        self.gridLayout_15.addWidget(self.label_treasure_type, 0, 0, 1, 1)
        self.gridLayout_14.addWidget(self.widget_7, 1, 1, 1, 1)
        self.widget_8 = QtGui.QWidget(self.treasure_generator_tab)
        self.widget_8.setObjectName(_fromUtf8("widget_8"))
        self.gridLayout_16 = QtGui.QGridLayout(self.widget_8)
        self.gridLayout_16.setMargin(0)
        self.gridLayout_16.setObjectName(_fromUtf8("gridLayout_16"))
        self.label_silver = QtGui.QLabel(self.widget_8)
        self.label_silver.setObjectName(_fromUtf8("label_silver"))
        self.gridLayout_16.addWidget(self.label_silver, 0, 1, 1, 1)
        self.label_gold = QtGui.QLabel(self.widget_8)
        self.label_gold.setObjectName(_fromUtf8("label_gold"))
        self.gridLayout_16.addWidget(self.label_gold, 0, 3, 1, 1)
        self.label_platinum = QtGui.QLabel(self.widget_8)
        self.label_platinum.setObjectName(_fromUtf8("label_platinum"))
        self.gridLayout_16.addWidget(self.label_platinum, 0, 4, 1, 1)
        self.label_copper = QtGui.QLabel(self.widget_8)
        self.label_copper.setObjectName(_fromUtf8("label_copper"))
        self.gridLayout_16.addWidget(self.label_copper, 0, 0, 1, 1)
        self.label_electrum = QtGui.QLabel(self.widget_8)
        self.label_electrum.setObjectName(_fromUtf8("label_electrum"))
        self.gridLayout_16.addWidget(self.label_electrum, 0, 2, 1, 1)
        self.lineedit_numberofcoins_copper = QtGui.QLineEdit(self.widget_8)
        self.lineedit_numberofcoins_copper.setObjectName(_fromUtf8("lineedit_numberofcoins_copper"))
        self.gridLayout_16.addWidget(self.lineedit_numberofcoins_copper, 1, 0, 1, 1)
        self.lineedit_numberofcoins_silver = QtGui.QLineEdit(self.widget_8)
        self.lineedit_numberofcoins_silver.setObjectName(_fromUtf8("lineedit_numberofcoins_silver"))
        self.gridLayout_16.addWidget(self.lineedit_numberofcoins_silver, 1, 1, 1, 1)
        self.lineedit_numberofcoins_electrum = QtGui.QLineEdit(self.widget_8)
        self.lineedit_numberofcoins_electrum.setObjectName(_fromUtf8("lineedit_numberofcoins_electrum"))
        self.gridLayout_16.addWidget(self.lineedit_numberofcoins_electrum, 1, 2, 1, 1)
        self.lineedit_numberofcoins_gold = QtGui.QLineEdit(self.widget_8)
        self.lineedit_numberofcoins_gold.setObjectName(_fromUtf8("lineedit_numberofcoins_gold"))
        self.gridLayout_16.addWidget(self.lineedit_numberofcoins_gold, 1, 3, 1, 1)
        self.lineedit_numberofcoins_platinum = QtGui.QLineEdit(self.widget_8)
        self.lineedit_numberofcoins_platinum.setObjectName(_fromUtf8("lineedit_numberofcoins_platinum"))
        self.gridLayout_16.addWidget(self.lineedit_numberofcoins_platinum, 1, 4, 1, 1)
        self.gridLayout_14.addWidget(self.widget_8, 2, 1, 1, 1)
        self.widget_9 = QtGui.QWidget(self.treasure_generator_tab)
        self.widget_9.setObjectName(_fromUtf8("widget_9"))
        self.gridLayout_17 = QtGui.QGridLayout(self.widget_9)
        self.gridLayout_17.setMargin(0)
        self.gridLayout_17.setObjectName(_fromUtf8("gridLayout_17"))
        self.label_gems = QtGui.QLabel(self.widget_9)
        self.label_gems.setObjectName(_fromUtf8("label_gems"))
        self.gridLayout_17.addWidget(self.label_gems, 0, 0, 1, 1)
        self.label_magicitems = QtGui.QLabel(self.widget_9)
        self.label_magicitems.setObjectName(_fromUtf8("label_magicitems"))
        self.gridLayout_17.addWidget(self.label_magicitems, 2, 0, 1, 1)
        self.label_jewels = QtGui.QLabel(self.widget_9)
        self.label_jewels.setObjectName(_fromUtf8("label_jewels"))
        self.gridLayout_17.addWidget(self.label_jewels, 1, 0, 1, 1)
        self.display_gems = QtGui.QTextBrowser(self.widget_9)
        self.display_gems.setObjectName(_fromUtf8("display_gems"))
        self.gridLayout_17.addWidget(self.display_gems, 0, 1, 1, 1)
        self.display_jewels = QtGui.QTextBrowser(self.widget_9)
        self.display_jewels.setObjectName(_fromUtf8("display_jewels"))
        self.gridLayout_17.addWidget(self.display_jewels, 1, 1, 1, 1)
        self.display_magicitems = QtGui.QTextBrowser(self.widget_9)
        self.display_magicitems.setObjectName(_fromUtf8("display_magicitems"))
        self.gridLayout_17.addWidget(self.display_magicitems, 2, 1, 1, 1)
        self.gridLayout_14.addWidget(self.widget_9, 3, 1, 1, 1)
        self.create_campain_tabs.addTab(self.treasure_generator_tab, _fromUtf8(""))
        self.disease_generator_tab = QtGui.QWidget()
        self.disease_generator_tab.setObjectName(_fromUtf8("disease_generator_tab"))
        self.create_campain_tabs.addTab(self.disease_generator_tab, _fromUtf8(""))
        self.npc_generator_tab = QtGui.QWidget()
        self.npc_generator_tab.setObjectName(_fromUtf8("npc_generator_tab"))
        self.gridLayout_18 = QtGui.QGridLayout(self.npc_generator_tab)
        self.gridLayout_18.setObjectName(_fromUtf8("gridLayout_18"))
        self.groupbox_parametersofgeneration = QtGui.QGroupBox(self.npc_generator_tab)
        self.groupbox_parametersofgeneration.setObjectName(_fromUtf8("groupbox_parametersofgeneration"))
        self.gridLayout_19 = QtGui.QGridLayout(self.groupbox_parametersofgeneration)
        self.gridLayout_19.setObjectName(_fromUtf8("gridLayout_19"))
        self.label_raceofnpc = QtGui.QLabel(self.groupbox_parametersofgeneration)
        self.label_raceofnpc.setObjectName(_fromUtf8("label_raceofnpc"))
        self.gridLayout_19.addWidget(self.label_raceofnpc, 2, 0, 1, 1)
        self.label_genderofnpc = QtGui.QLabel(self.groupbox_parametersofgeneration)
        self.label_genderofnpc.setObjectName(_fromUtf8("label_genderofnpc"))
        self.gridLayout_19.addWidget(self.label_genderofnpc, 1, 0, 1, 1)
        self.combobox_genderofnpc = QtGui.QComboBox(self.groupbox_parametersofgeneration)
        self.combobox_genderofnpc.setObjectName(_fromUtf8("combobox_genderofnpc"))
        self.combobox_genderofnpc.addItem(_fromUtf8(""))
        self.combobox_genderofnpc.addItem(_fromUtf8(""))
        self.combobox_genderofnpc.addItem(_fromUtf8(""))
        self.gridLayout_19.addWidget(self.combobox_genderofnpc, 1, 1, 1, 1)
        self.label_alignmentofnpc = QtGui.QLabel(self.groupbox_parametersofgeneration)
        self.label_alignmentofnpc.setObjectName(_fromUtf8("label_alignmentofnpc"))
        self.gridLayout_19.addWidget(self.label_alignmentofnpc, 0, 0, 1, 1)
        self.combobox_raceofnpc = QtGui.QComboBox(self.groupbox_parametersofgeneration)
        self.combobox_raceofnpc.setObjectName(_fromUtf8("combobox_raceofnpc"))
        self.combobox_raceofnpc.addItem(_fromUtf8(""))
        self.combobox_raceofnpc.addItem(_fromUtf8(""))
        self.combobox_raceofnpc.addItem(_fromUtf8(""))
        self.combobox_raceofnpc.addItem(_fromUtf8(""))
        self.combobox_raceofnpc.addItem(_fromUtf8(""))
        self.gridLayout_19.addWidget(self.combobox_raceofnpc, 2, 1, 1, 1)
        self.combobox_alignmentofnpc = QtGui.QComboBox(self.groupbox_parametersofgeneration)
        self.combobox_alignmentofnpc.setObjectName(_fromUtf8("combobox_alignmentofnpc"))
        self.combobox_alignmentofnpc.addItem(_fromUtf8(""))
        self.combobox_alignmentofnpc.addItem(_fromUtf8(""))
        self.combobox_alignmentofnpc.addItem(_fromUtf8(""))
        self.combobox_alignmentofnpc.addItem(_fromUtf8(""))
        self.combobox_alignmentofnpc.addItem(_fromUtf8(""))
        self.combobox_alignmentofnpc.addItem(_fromUtf8(""))
        self.combobox_alignmentofnpc.addItem(_fromUtf8(""))
        self.combobox_alignmentofnpc.addItem(_fromUtf8(""))
        self.combobox_alignmentofnpc.addItem(_fromUtf8(""))
        self.combobox_alignmentofnpc.addItem(_fromUtf8(""))
        self.combobox_alignmentofnpc.addItem(_fromUtf8(""))
        self.combobox_alignmentofnpc.addItem(_fromUtf8(""))
        self.combobox_alignmentofnpc.addItem(_fromUtf8(""))
        self.gridLayout_19.addWidget(self.combobox_alignmentofnpc, 0, 1, 1, 1)
        self.label_classofnpc = QtGui.QLabel(self.groupbox_parametersofgeneration)
        self.label_classofnpc.setObjectName(_fromUtf8("label_classofnpc"))
        self.gridLayout_19.addWidget(self.label_classofnpc, 0, 2, 1, 1)
        self.combobox_classofnpc = QtGui.QComboBox(self.groupbox_parametersofgeneration)
        self.combobox_classofnpc.setObjectName(_fromUtf8("combobox_classofnpc"))
        self.combobox_classofnpc.addItem(_fromUtf8(""))
        self.combobox_classofnpc.addItem(_fromUtf8(""))
        self.combobox_classofnpc.addItem(_fromUtf8(""))
        self.combobox_classofnpc.addItem(_fromUtf8(""))
        self.combobox_classofnpc.addItem(_fromUtf8(""))
        self.gridLayout_19.addWidget(self.combobox_classofnpc, 0, 3, 1, 1)
        self.label_levelofnpc = QtGui.QLabel(self.groupbox_parametersofgeneration)
        self.label_levelofnpc.setObjectName(_fromUtf8("label_levelofnpc"))
        self.gridLayout_19.addWidget(self.label_levelofnpc, 1, 2, 1, 1)
        self.layout_levelofnpc = QtGui.QHBoxLayout()
        self.layout_levelofnpc.setObjectName(_fromUtf8("layout_levelofnpc"))
        self.slider_levelofnpc = QtGui.QSlider(self.groupbox_parametersofgeneration)
        self.slider_levelofnpc.setMinimum(1)
        self.slider_levelofnpc.setMaximum(20)
        self.slider_levelofnpc.setOrientation(QtCore.Qt.Horizontal)
        self.slider_levelofnpc.setObjectName(_fromUtf8("slider_levelofnpc"))
        self.layout_levelofnpc.addWidget(self.slider_levelofnpc)
        self.label_level_number = QtGui.QLabel(self.groupbox_parametersofgeneration)
        self.label_level_number.setObjectName(_fromUtf8("label_level_number"))
        self.layout_levelofnpc.addWidget(self.label_level_number)
        self.gridLayout_19.addLayout(self.layout_levelofnpc, 1, 3, 1, 1)
        self.label_statsofnpc = QtGui.QLabel(self.groupbox_parametersofgeneration)
        self.label_statsofnpc.setObjectName(_fromUtf8("label_statsofnpc"))
        self.gridLayout_19.addWidget(self.label_statsofnpc, 2, 2, 1, 1)
        self.combobox_statsofnpc = QtGui.QComboBox(self.groupbox_parametersofgeneration)
        self.combobox_statsofnpc.setObjectName(_fromUtf8("combobox_statsofnpc"))
        self.combobox_statsofnpc.addItem(_fromUtf8(""))
        self.combobox_statsofnpc.addItem(_fromUtf8(""))
        self.combobox_statsofnpc.addItem(_fromUtf8(""))
        self.combobox_statsofnpc.addItem(_fromUtf8(""))
        self.combobox_statsofnpc.addItem(_fromUtf8(""))
        self.gridLayout_19.addWidget(self.combobox_statsofnpc, 2, 3, 1, 1)
        self.gridLayout_18.addWidget(self.groupbox_parametersofgeneration, 0, 0, 1, 1)
        self.display_generated_npc = QtGui.QTextBrowser(self.npc_generator_tab)
        self.display_generated_npc.setObjectName(_fromUtf8("display_generated_npc"))
        self.gridLayout_18.addWidget(self.display_generated_npc, 1, 0, 1, 1)
        self.create_campain_tabs.addTab(self.npc_generator_tab, _fromUtf8(""))
        self.background_tab = QtGui.QWidget()
        self.background_tab.setObjectName(_fromUtf8("background_tab"))
        self.gridLayout = QtGui.QGridLayout(self.background_tab)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.textedit_background = QtGui.QPlainTextEdit(self.background_tab)
        self.textedit_background.setObjectName(_fromUtf8("textedit_background"))
        self.gridLayout.addWidget(self.textedit_background, 3, 0, 1, 1)
        self.verticalscrollbar_background = QtGui.QScrollBar(self.background_tab)
        self.verticalscrollbar_background.setOrientation(QtCore.Qt.Vertical)
        self.verticalscrollbar_background.setObjectName(_fromUtf8("verticalscrollbar_background"))
        self.gridLayout.addWidget(self.verticalscrollbar_background, 3, 1, 1, 1)
        self.font_background = QtGui.QFontComboBox(self.background_tab)
        self.font_background.setObjectName(_fromUtf8("font_background"))
        self.gridLayout.addWidget(self.font_background, 0, 0, 1, 1)
        self.create_campain_tabs.addTab(self.background_tab, _fromUtf8(""))
        self.gridLayout_2.addWidget(self.create_campain_tabs, 0, 0, 1, 1)
        self.dock_campain.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(4), self.dock_campain)
        self.dock_client = QtGui.QDockWidget(MainWindow)
        self.dock_client.setEnabled(True)
        self.dock_client.setObjectName(_fromUtf8("dock_client"))
        self.dockWidgetContents_3 = QtGui.QWidget()
        self.dockWidgetContents_3.setObjectName(_fromUtf8("dockWidgetContents_3"))
        self.gridLayout_7 = QtGui.QGridLayout(self.dockWidgetContents_3)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.groupBox_2 = QtGui.QGroupBox(self.dockWidgetContents_3)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_11 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.graphicsView_2 = QtGui.QGraphicsView(self.groupBox_2)
        self.graphicsView_2.setObjectName(_fromUtf8("graphicsView_2"))
        self.gridLayout_11.addWidget(self.graphicsView_2, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.groupBox_2)
        self.groupBox = QtGui.QGroupBox(self.dockWidgetContents_3)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_12 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_32 = QtGui.QLabel(self.groupBox)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.horizontalLayout_5.addWidget(self.label_32)
        self.label_27 = QtGui.QLabel(self.groupBox)
        self.label_27.setFrameShape(QtGui.QFrame.WinPanel)
        self.label_27.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.horizontalLayout_5.addWidget(self.label_27)
        self.gridLayout_12.addLayout(self.horizontalLayout_5, 7, 0, 1, 1)
        self.pushButton_2 = QtGui.QPushButton(self.groupBox)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/images/dices/d6.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon9)
        self.pushButton_2.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.gridLayout_12.addWidget(self.pushButton_2, 3, 1, 1, 1)
        self.pushButton_4 = QtGui.QPushButton(self.groupBox)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/images/dices/d10.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon10)
        self.pushButton_4.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.gridLayout_12.addWidget(self.pushButton_4, 4, 1, 1, 1)
        self.pushButton_5 = QtGui.QPushButton(self.groupBox)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/images/dices/d12.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_5.setIcon(icon11)
        self.pushButton_5.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.gridLayout_12.addWidget(self.pushButton_5, 5, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_12.addWidget(self.label_4, 0, 0, 1, 1)
        self.pushButton_3 = QtGui.QPushButton(self.groupBox)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/images/dices/d8.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon12)
        self.pushButton_3.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.gridLayout_12.addWidget(self.pushButton_3, 4, 0, 1, 1)
        self.pushButton = QtGui.QPushButton(self.groupBox)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/images/dices/d4.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon13)
        self.pushButton.setIconSize(QtCore.QSize(32, 32))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.gridLayout_12.addWidget(self.pushButton, 3, 0, 1, 1)
        self.spinBox_3 = QtGui.QSpinBox(self.groupBox)
        self.spinBox_3.setMinimum(-9999)
        self.spinBox_3.setMaximum(9999)
        self.spinBox_3.setObjectName(_fromUtf8("spinBox_3"))
        self.gridLayout_12.addWidget(self.spinBox_3, 0, 1, 1, 1)
        self.spinBox = QtGui.QSpinBox(self.groupBox)
        self.spinBox.setObjectName(_fromUtf8("spinBox"))
        self.gridLayout_12.addWidget(self.spinBox, 1, 1, 1, 1)
        self.spinBox_2 = QtGui.QSpinBox(self.groupBox)
        self.spinBox_2.setObjectName(_fromUtf8("spinBox_2"))
        self.gridLayout_12.addWidget(self.spinBox_2, 2, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_12.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_12.addWidget(self.label_3, 2, 0, 1, 1)
        self.pushButton_6 = QtGui.QPushButton(self.groupBox)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/images/dices/d20.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_6.setIcon(icon14)
        self.pushButton_6.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.gridLayout_12.addWidget(self.pushButton_6, 5, 1, 1, 1)
        self.pushButton_7 = QtGui.QPushButton(self.groupBox)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/images/dices/d100.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_7.setIcon(icon15)
        self.pushButton_7.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_7.setObjectName(_fromUtf8("pushButton_7"))
        self.gridLayout_12.addWidget(self.pushButton_7, 6, 0, 1, 1)
        self.pushButton_8 = QtGui.QPushButton(self.groupBox)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/images/dices/custom.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_8.setIcon(icon16)
        self.pushButton_8.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_8.setObjectName(_fromUtf8("pushButton_8"))
        self.gridLayout_12.addWidget(self.pushButton_8, 6, 1, 1, 1)
        self.checkBox = QtGui.QCheckBox(self.groupBox)
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.gridLayout_12.addWidget(self.checkBox, 7, 1, 1, 1)
        self.horizontalLayout.addWidget(self.groupBox)
        self.gridLayout_7.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.tab_character_sheets = QtGui.QTabWidget(self.dockWidgetContents_3)
        self.tab_character_sheets.setObjectName(_fromUtf8("tab_character_sheets"))
        self.character_sheet_1 = QtGui.QWidget()
        self.character_sheet_1.setObjectName(_fromUtf8("character_sheet_1"))
        self.gridLayout_20 = QtGui.QGridLayout(self.character_sheet_1)
        self.gridLayout_20.setObjectName(_fromUtf8("gridLayout_20"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_5 = QtGui.QLabel(self.character_sheet_1)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_2.addWidget(self.label_5)
        self.lineEdit = QtGui.QLineEdit(self.character_sheet_1)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.horizontalLayout_2.addWidget(self.lineEdit)
        self.label_6 = QtGui.QLabel(self.character_sheet_1)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_2.addWidget(self.label_6)
        self.lineEdit_2 = QtGui.QLineEdit(self.character_sheet_1)
        self.lineEdit_2.setInputMask(_fromUtf8(""))
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.horizontalLayout_2.addWidget(self.lineEdit_2)
        self.label_7 = QtGui.QLabel(self.character_sheet_1)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_2.addWidget(self.label_7)
        self.lineEdit_3 = QtGui.QLineEdit(self.character_sheet_1)
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.horizontalLayout_2.addWidget(self.lineEdit_3)
        self.toolbutton_charactersheet_options = QtGui.QToolButton(self.character_sheet_1)
        self.toolbutton_charactersheet_options.setObjectName(_fromUtf8("toolbutton_charactersheet_options"))
        self.horizontalLayout_2.addWidget(self.toolbutton_charactersheet_options)
        self.gridLayout_20.addLayout(self.horizontalLayout_2, 0, 2, 1, 1)
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.gridLayout_21 = QtGui.QGridLayout()
        self.gridLayout_21.setObjectName(_fromUtf8("gridLayout_21"))
        self.label = QtGui.QLabel(self.character_sheet_1)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_21.addWidget(self.label, 0, 0, 1, 1)
        self.progressBar = QtGui.QProgressBar(self.character_sheet_1)
        self.progressBar.setMaximum(8)
        self.progressBar.setProperty("value", 8)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.gridLayout_21.addWidget(self.progressBar, 0, 1, 1, 1)
        self.spinBox_4 = QtGui.QSpinBox(self.character_sheet_1)
        self.spinBox_4.setMaximum(999)
        self.spinBox_4.setProperty("value", 8)
        self.spinBox_4.setObjectName(_fromUtf8("spinBox_4"))
        self.gridLayout_21.addWidget(self.spinBox_4, 0, 2, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_21, 0, 0, 1, 1)
        self.gridLayout_22 = QtGui.QGridLayout()
        self.gridLayout_22.setObjectName(_fromUtf8("gridLayout_22"))
        self.label_19 = QtGui.QLabel(self.character_sheet_1)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout_22.addWidget(self.label_19, 6, 2, 1, 1)
        self.label_18 = QtGui.QLabel(self.character_sheet_1)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_22.addWidget(self.label_18, 5, 2, 1, 1)
        self.label_17 = QtGui.QLabel(self.character_sheet_1)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_22.addWidget(self.label_17, 4, 2, 1, 1)
        self.label_12 = QtGui.QLabel(self.character_sheet_1)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_22.addWidget(self.label_12, 6, 0, 1, 1)
        self.label_9 = QtGui.QLabel(self.character_sheet_1)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_22.addWidget(self.label_9, 2, 0, 1, 1)
        self.label_13 = QtGui.QLabel(self.character_sheet_1)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_22.addWidget(self.label_13, 4, 0, 1, 1)
        self.label_10 = QtGui.QLabel(self.character_sheet_1)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_22.addWidget(self.label_10, 3, 0, 1, 1)
        self.label_11 = QtGui.QLabel(self.character_sheet_1)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_22.addWidget(self.label_11, 5, 0, 1, 1)
        self.lineEdit_6 = QtGui.QLineEdit(self.character_sheet_1)
        self.lineEdit_6.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.lineEdit_6.setObjectName(_fromUtf8("lineEdit_6"))
        self.gridLayout_22.addWidget(self.lineEdit_6, 3, 1, 1, 1)
        self.label_16 = QtGui.QLabel(self.character_sheet_1)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_22.addWidget(self.label_16, 3, 2, 1, 1)
        self.lineEdit_9 = QtGui.QLineEdit(self.character_sheet_1)
        self.lineEdit_9.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.lineEdit_9.setObjectName(_fromUtf8("lineEdit_9"))
        self.gridLayout_22.addWidget(self.lineEdit_9, 6, 1, 1, 1)
        self.lineEdit_8 = QtGui.QLineEdit(self.character_sheet_1)
        self.lineEdit_8.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.lineEdit_8.setObjectName(_fromUtf8("lineEdit_8"))
        self.gridLayout_22.addWidget(self.lineEdit_8, 5, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.character_sheet_1)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_22.addWidget(self.label_8, 1, 0, 1, 1)
        self.label_15 = QtGui.QLabel(self.character_sheet_1)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_22.addWidget(self.label_15, 2, 2, 1, 1)
        self.label_14 = QtGui.QLabel(self.character_sheet_1)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_22.addWidget(self.label_14, 1, 2, 1, 1)
        self.lineEdit_4 = QtGui.QLineEdit(self.character_sheet_1)
        self.lineEdit_4.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.gridLayout_22.addWidget(self.lineEdit_4, 1, 1, 1, 1)
        self.lineEdit_7 = QtGui.QLineEdit(self.character_sheet_1)
        self.lineEdit_7.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.lineEdit_7.setObjectName(_fromUtf8("lineEdit_7"))
        self.gridLayout_22.addWidget(self.lineEdit_7, 4, 1, 1, 1)
        self.lineEdit_5 = QtGui.QLineEdit(self.character_sheet_1)
        self.lineEdit_5.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.lineEdit_5.setObjectName(_fromUtf8("lineEdit_5"))
        self.gridLayout_22.addWidget(self.lineEdit_5, 2, 1, 1, 1)
        self.lineEdit_10 = QtGui.QLineEdit(self.character_sheet_1)
        self.lineEdit_10.setObjectName(_fromUtf8("lineEdit_10"))
        self.gridLayout_22.addWidget(self.lineEdit_10, 2, 3, 1, 1)
        self.lineEdit_11 = QtGui.QLineEdit(self.character_sheet_1)
        self.lineEdit_11.setObjectName(_fromUtf8("lineEdit_11"))
        self.gridLayout_22.addWidget(self.lineEdit_11, 3, 3, 1, 1)
        self.lineEdit_12 = QtGui.QLineEdit(self.character_sheet_1)
        self.lineEdit_12.setObjectName(_fromUtf8("lineEdit_12"))
        self.gridLayout_22.addWidget(self.lineEdit_12, 4, 3, 1, 1)
        self.lineEdit_13 = QtGui.QLineEdit(self.character_sheet_1)
        self.lineEdit_13.setObjectName(_fromUtf8("lineEdit_13"))
        self.gridLayout_22.addWidget(self.lineEdit_13, 5, 3, 1, 1)
        self.lineEdit_14 = QtGui.QLineEdit(self.character_sheet_1)
        self.lineEdit_14.setObjectName(_fromUtf8("lineEdit_14"))
        self.gridLayout_22.addWidget(self.lineEdit_14, 6, 3, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_22, 1, 0, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_20 = QtGui.QLabel(self.character_sheet_1)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.horizontalLayout_3.addWidget(self.label_20)
        self.spinBox_5 = QtGui.QSpinBox(self.character_sheet_1)
        self.spinBox_5.setSuffix(_fromUtf8(""))
        self.spinBox_5.setMinimum(-999)
        self.spinBox_5.setMaximum(9)
        self.spinBox_5.setProperty("value", 9)
        self.spinBox_5.setObjectName(_fromUtf8("spinBox_5"))
        self.horizontalLayout_3.addWidget(self.spinBox_5)
        self.label_21 = QtGui.QLabel(self.character_sheet_1)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.horizontalLayout_3.addWidget(self.label_21)
        self.comboBox = QtGui.QComboBox(self.character_sheet_1)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.horizontalLayout_3.addWidget(self.comboBox)
        self.label_22 = QtGui.QLabel(self.character_sheet_1)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.horizontalLayout_3.addWidget(self.label_22)
        self.comboBox_2 = QtGui.QComboBox(self.character_sheet_1)
        self.comboBox_2.setObjectName(_fromUtf8("comboBox_2"))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.horizontalLayout_3.addWidget(self.comboBox_2)
        self.label_23 = QtGui.QLabel(self.character_sheet_1)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.horizontalLayout_3.addWidget(self.label_23)
        self.comboBox_3 = QtGui.QComboBox(self.character_sheet_1)
        self.comboBox_3.setObjectName(_fromUtf8("comboBox_3"))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.horizontalLayout_3.addWidget(self.comboBox_3)
        self.label_25 = QtGui.QLabel(self.character_sheet_1)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.horizontalLayout_3.addWidget(self.label_25)
        self.label_26 = QtGui.QLabel(self.character_sheet_1)
        self.label_26.setFrameShape(QtGui.QFrame.WinPanel)
        self.label_26.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.horizontalLayout_3.addWidget(self.label_26)
        self.gridLayout_5.addLayout(self.horizontalLayout_3, 0, 1, 1, 1)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_24 = QtGui.QLabel(self.character_sheet_1)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.verticalLayout.addWidget(self.label_24)
        self.plainTextEdit = QtGui.QPlainTextEdit(self.character_sheet_1)
        self.plainTextEdit.setObjectName(_fromUtf8("plainTextEdit"))
        self.verticalLayout.addWidget(self.plainTextEdit)
        self.gridLayout_5.addLayout(self.verticalLayout, 1, 1, 1, 1)
        self.gridLayout_20.addLayout(self.gridLayout_5, 1, 2, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_28 = QtGui.QLabel(self.character_sheet_1)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.horizontalLayout_4.addWidget(self.label_28)
        self.lineEdit_15 = QtGui.QLineEdit(self.character_sheet_1)
        self.lineEdit_15.setObjectName(_fromUtf8("lineEdit_15"))
        self.horizontalLayout_4.addWidget(self.lineEdit_15)
        self.label_29 = QtGui.QLabel(self.character_sheet_1)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.horizontalLayout_4.addWidget(self.label_29)
        self.label_30 = QtGui.QLabel(self.character_sheet_1)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.horizontalLayout_4.addWidget(self.label_30)
        self.label_31 = QtGui.QLabel(self.character_sheet_1)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.horizontalLayout_4.addWidget(self.label_31)
        self.gridLayout_20.addLayout(self.horizontalLayout_4, 2, 2, 1, 1)
        self.tab_character_sheets.addTab(self.character_sheet_1, _fromUtf8(""))
        self.gridLayout_7.addWidget(self.tab_character_sheets, 2, 0, 1, 1)
        self.dock_client.setWidget(self.dockWidgetContents_3)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.dock_client)
        self.actionNew_Campain = QtGui.QAction(MainWindow)
        self.actionNew_Campain.setObjectName(_fromUtf8("actionNew_Campain"))
        self.actionSave_Campain = QtGui.QAction(MainWindow)
        self.actionSave_Campain.setObjectName(_fromUtf8("actionSave_Campain"))
        self.actionLoad_Campain = QtGui.QAction(MainWindow)
        self.actionLoad_Campain.setObjectName(_fromUtf8("actionLoad_Campain"))
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionHost_Game = QtGui.QAction(MainWindow)
        self.actionHost_Game.setObjectName(_fromUtf8("actionHost_Game"))
        self.actionConnect_to = QtGui.QAction(MainWindow)
        self.actionConnect_to.setObjectName(_fromUtf8("actionConnect_to"))
        self.actionHelp = QtGui.QAction(MainWindow)
        self.actionHelp.setObjectName(_fromUtf8("actionHelp"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.menuFile.addAction(self.actionNew_Campain)
        self.menuFile.addAction(self.actionSave_Campain)
        self.menuFile.addAction(self.actionLoad_Campain)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuConnect.addAction(self.actionHost_Game)
        self.menuConnect.addSeparator()
        self.menuConnect.addAction(self.actionConnect_to)
        self.menuHelp.addAction(self.actionHelp)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuConnect.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.create_campain_tabs.setCurrentIndex(0)
        self.toolbox_tabs.setCurrentIndex(0)
        self.tab_character_sheets.setCurrentIndex(0)
        QtCore.QObject.connect(self.actionNew_Campain, QtCore.SIGNAL(_fromUtf8("activated()")), self.dock_campain.show)
        QtCore.QObject.connect(self.slider_levelofnpc, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.label_level_number.setNum)
        QtCore.QObject.connect(self.slider_chanceofencounter, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.label_display_chanceofencounter.setNum)
        QtCore.QObject.connect(self.actionQuit, QtCore.SIGNAL(_fromUtf8("activated()")), MainWindow.close)
        QtCore.QObject.connect(self.actionSave_Campain, QtCore.SIGNAL(_fromUtf8("activated()")), self.dock_campain.raise_)
        QtCore.QObject.connect(self.spinBox_4, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.progressBar.setMaximum)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Dungeon and Dragons", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuConnect.setTitle(_translate("MainWindow", "Connect", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))
        self.dock_campain.setWindowTitle(_translate("MainWindow", "Campain Editor", None))
        self.groubox_toolbox.setTitle(_translate("MainWindow", "ToolBox", None))
        self.toolbox_tabs.setTabText(self.toolbox_tabs.indexOf(self.door_tab), _translate("MainWindow", "Doors", None))
        self.toolbox_tabs.setTabText(self.toolbox_tabs.indexOf(self.tab_2), _translate("MainWindow", "Page", None))
        self.toolbox_tabs.setTabText(self.toolbox_tabs.indexOf(self.tab_3), _translate("MainWindow", "Page", None))
        self.toolbox_radio_paper_empty.setText(_translate("MainWindow", "Empty", None))
        self.toolbox_radio_paper_square.setText(_translate("MainWindow", "Squares", None))
        self.toolbox_radio_paper_hexagonal.setText(_translate("MainWindow", "Hexagonal", None))
        self.create_campain_tabs.setTabText(self.create_campain_tabs.indexOf(self.map_designer_tab), _translate("MainWindow", "Map Designer", None))
        self.label_environmentofencounter.setText(_translate("MainWindow", "Environement of Encounter", None))
        self.group_generatedtable.setTitle(_translate("MainWindow", "Generated Table", None))
        self.label_generatedtable_1.setText(_translate("MainWindow", "1 :", None))
        self.label_nameofrolledmonster_1.setText(_translate("MainWindow", "_", None))
        self.label_generatedtable_2.setText(_translate("MainWindow", "2 :", None))
        self.label_nameofrolledmonster_2.setText(_translate("MainWindow", "_", None))
        self.label_generatedtable_3.setText(_translate("MainWindow", "3 :", None))
        self.label_nameofrolledmonster_3.setText(_translate("MainWindow", "_", None))
        self.label_generatedtable_4.setText(_translate("MainWindow", "4 :", None))
        self.label_nameofrolledmonster_4.setText(_translate("MainWindow", "_", None))
        self.label_generatedtable_5.setText(_translate("MainWindow", "5 :", None))
        self.label_nameofrolledmonster_5.setText(_translate("MainWindow", "_", None))
        self.label_generatedtable_6.setText(_translate("MainWindow", "6 :", None))
        self.label_nameofrolledmonster_6.setText(_translate("MainWindow", "_", None))
        self.label_generatedtable_7.setText(_translate("MainWindow", "7 :", None))
        self.label_nameofrolledmonster_7.setText(_translate("MainWindow", "_", None))
        self.label_generatedtable_8.setText(_translate("MainWindow", "8 :", None))
        self.label_nameofrolledmonster_8.setText(_translate("MainWindow", "_", None))
        self.label_generatedtable_9.setText(_translate("MainWindow", "9 :", None))
        self.label_nameofrolledmonster_9.setText(_translate("MainWindow", "_", None))
        self.label_generatedtable_10.setText(_translate("MainWindow", "10 :", None))
        self.label_nameofrolledmonster_10.setText(_translate("MainWindow", "_", None))
        self.label_generatedtable_11.setText(_translate("MainWindow", "11 :", None))
        self.label_nameofrolledmonster_11.setText(_translate("MainWindow", "_", None))
        self.label_generatedtable_12.setText(_translate("MainWindow", "12 :", None))
        self.label_nameofrolledmonster_12.setText(_translate("MainWindow", "_", None))
        self.button_rollamonster.setText(_translate("MainWindow", "Roll a Monster", None))
        self.button_rollatable.setText(_translate("MainWindow", "Roll a Table", None))
        self.group_statsofrolledmonster.setTitle(_translate("MainWindow", "Stats of the Rolled Monster", None))
        self.label_statsofrolledmonster_treasurevalue.setText(_translate("MainWindow", "Treasure Value :", None))
        self.monster_xp_value.setText(_translate("MainWindow", "_", None))
        self.label_statsofrolledmonster_hp.setText(_translate("MainWindow", "HP :", None))
        self.monster_ac_value.setText(_translate("MainWindow", "_", None))
        self.label_statsofrolledmonster_xpvalue.setText(_translate("MainWindow", "XP Value :", None))
        self.monster_alignment_value.setText(_translate("MainWindow", "_", None))
        self.label_statsofrolledmonster_ac.setText(_translate("MainWindow", "AC :", None))
        self.monster_moral_value.setText(_translate("MainWindow", "_", None))
        self.monster_attack_value.setText(_translate("MainWindow", "_", None))
        self.label_statsofrolledmonster_moral.setText(_translate("MainWindow", "Moral :", None))
        self.label_statsofrolledmonster_attacks.setText(_translate("MainWindow", "Attacks :", None))
        self.monster_movement_value.setText(_translate("MainWindow", "_", None))
        self.label_statsofrolledmonster_movement.setText(_translate("MainWindow", "Movement", None))
        self.label_statsofrolledmonster_alignment.setText(_translate("MainWindow", "Alignment :", None))
        self.monster_damages_value.setText(_translate("MainWindow", "_", None))
        self.label_statsofrolledmonster_damages.setText(_translate("MainWindow", "Damages :", None))
        self.label_statsofrolledmonster_saves.setText(_translate("MainWindow", "Saves :", None))
        self.monster_saves_poison_value.setText(_translate("MainWindow", "_", None))
        self.label_monster_saves_poi.setText(_translate("MainWindow", "Poison/Deathray", None))
        self.label_monster_saves_dra.setText(_translate("MainWindow", "Dragon Breath", None))
        self.label_monster_saves_par.setText(_translate("MainWindow", "Paralysis", None))
        self.label_monster_saves_wan.setText(_translate("MainWindow", "Wands", None))
        self.label_monster_saves_spe.setText(_translate("MainWindow", "Spells", None))
        self.monster_saves_wands_value.setText(_translate("MainWindow", "_", None))
        self.monster_saves_paralysis_value.setText(_translate("MainWindow", "_", None))
        self.monster_saves_dragonbreath_value.setText(_translate("MainWindow", "_", None))
        self.monster_saves_spells_value.setText(_translate("MainWindow", "_", None))
        self.spin_damagetoinflict.setSuffix(_translate("MainWindow", " DMG", None))
        self.button_inflictdamage.setText(_translate("MainWindow", "Hit", None))
        self.monster_treasure_value.setText(_translate("MainWindow", "_", None))
        self.combo_environmentofencounter.setItemText(0, _translate("MainWindow", "Forest", None))
        self.combo_environmentofencounter.setItemText(1, _translate("MainWindow", "Swamp", None))
        self.combo_environmentofencounter.setItemText(2, _translate("MainWindow", "Mountain", None))
        self.combo_environmentofencounter.setItemText(3, _translate("MainWindow", "Desert (Warm)", None))
        self.combo_environmentofencounter.setItemText(4, _translate("MainWindow", "Desert (Cold)", None))
        self.combo_environmentofencounter.setItemText(5, _translate("MainWindow", "City", None))
        self.combo_environmentofencounter.setItemText(6, _translate("MainWindow", "Dungeon", None))
        self.combo_environmentofencounter.setItemText(7, _translate("MainWindow", "Lair (Insect)", None))
        self.combo_environmentofencounter.setItemText(8, _translate("MainWindow", "Lair (Gobelin)", None))
        self.label_chanceofencounter.setText(_translate("MainWindow", "Chance of Encounter", None))
        self.label_display_chanceofencounter.setText(_translate("MainWindow", "10", None))
        self.create_campain_tabs.setTabText(self.create_campain_tabs.indexOf(self.random_encounters_tab), _translate("MainWindow", "Random Encounters", None))
        self.combobox_treasure_type.setItemText(0, _translate("MainWindow", "A", None))
        self.combobox_treasure_type.setItemText(1, _translate("MainWindow", "B", None))
        self.combobox_treasure_type.setItemText(2, _translate("MainWindow", "C", None))
        self.combobox_treasure_type.setItemText(3, _translate("MainWindow", "D", None))
        self.combobox_treasure_type.setItemText(4, _translate("MainWindow", "E", None))
        self.combobox_treasure_type.setItemText(5, _translate("MainWindow", "F", None))
        self.combobox_treasure_type.setItemText(6, _translate("MainWindow", "G", None))
        self.combobox_treasure_type.setItemText(7, _translate("MainWindow", "H", None))
        self.combobox_treasure_type.setItemText(8, _translate("MainWindow", "I", None))
        self.combobox_treasure_type.setItemText(9, _translate("MainWindow", "J", None))
        self.combobox_treasure_type.setItemText(10, _translate("MainWindow", "K", None))
        self.combobox_treasure_type.setItemText(11, _translate("MainWindow", "L", None))
        self.combobox_treasure_type.setItemText(12, _translate("MainWindow", "M", None))
        self.combobox_treasure_type.setItemText(13, _translate("MainWindow", "N", None))
        self.combobox_treasure_type.setItemText(14, _translate("MainWindow", "O", None))
        self.combobox_treasure_type.setItemText(15, _translate("MainWindow", "P", None))
        self.combobox_treasure_type.setItemText(16, _translate("MainWindow", "Q", None))
        self.combobox_treasure_type.setItemText(17, _translate("MainWindow", "R", None))
        self.combobox_treasure_type.setItemText(18, _translate("MainWindow", "S", None))
        self.combobox_treasure_type.setItemText(19, _translate("MainWindow", "T", None))
        self.combobox_treasure_type.setItemText(20, _translate("MainWindow", "U", None))
        self.combobox_treasure_type.setItemText(21, _translate("MainWindow", "V", None))
        self.label_treasure_type.setText(_translate("MainWindow", "Treasure Type :", None))
        self.label_silver.setText(_translate("MainWindow", "Silver Coins", None))
        self.label_gold.setText(_translate("MainWindow", "Golden Coins", None))
        self.label_platinum.setText(_translate("MainWindow", "Platinum Coins", None))
        self.label_copper.setText(_translate("MainWindow", "Copper Coins", None))
        self.label_electrum.setText(_translate("MainWindow", "Electrum Coins", None))
        self.label_gems.setText(_translate("MainWindow", "Gems :", None))
        self.label_magicitems.setText(_translate("MainWindow", "Magic Items :", None))
        self.label_jewels.setText(_translate("MainWindow", "Jewels :", None))
        self.create_campain_tabs.setTabText(self.create_campain_tabs.indexOf(self.treasure_generator_tab), _translate("MainWindow", "Treasure Generator", None))
        self.create_campain_tabs.setTabText(self.create_campain_tabs.indexOf(self.disease_generator_tab), _translate("MainWindow", "Disease Generator", None))
        self.groupbox_parametersofgeneration.setTitle(_translate("MainWindow", "Parameters of generation", None))
        self.label_raceofnpc.setText(_translate("MainWindow", "Race :", None))
        self.label_genderofnpc.setText(_translate("MainWindow", "Gender :", None))
        self.combobox_genderofnpc.setItemText(0, _translate("MainWindow", "Any", None))
        self.combobox_genderofnpc.setItemText(1, _translate("MainWindow", "Male", None))
        self.combobox_genderofnpc.setItemText(2, _translate("MainWindow", "Female", None))
        self.label_alignmentofnpc.setText(_translate("MainWindow", "Alignment :", None))
        self.combobox_raceofnpc.setItemText(0, _translate("MainWindow", "Any", None))
        self.combobox_raceofnpc.setItemText(1, _translate("MainWindow", "Human", None))
        self.combobox_raceofnpc.setItemText(2, _translate("MainWindow", "Elf", None))
        self.combobox_raceofnpc.setItemText(3, _translate("MainWindow", "Dwarf", None))
        self.combobox_raceofnpc.setItemText(4, _translate("MainWindow", "Halfelin", None))
        self.combobox_alignmentofnpc.setItemText(0, _translate("MainWindow", "Any", None))
        self.combobox_alignmentofnpc.setItemText(1, _translate("MainWindow", "Any Lawful", None))
        self.combobox_alignmentofnpc.setItemText(2, _translate("MainWindow", "Any Neutral", None))
        self.combobox_alignmentofnpc.setItemText(3, _translate("MainWindow", "Any Chaotic", None))
        self.combobox_alignmentofnpc.setItemText(4, _translate("MainWindow", "Lawful Good", None))
        self.combobox_alignmentofnpc.setItemText(5, _translate("MainWindow", "Lawful Neutral", None))
        self.combobox_alignmentofnpc.setItemText(6, _translate("MainWindow", "Lawful Evil", None))
        self.combobox_alignmentofnpc.setItemText(7, _translate("MainWindow", "Neutral Good", None))
        self.combobox_alignmentofnpc.setItemText(8, _translate("MainWindow", "Neutral Neutral", None))
        self.combobox_alignmentofnpc.setItemText(9, _translate("MainWindow", "Neutral Evil", None))
        self.combobox_alignmentofnpc.setItemText(10, _translate("MainWindow", "Chaotic Good", None))
        self.combobox_alignmentofnpc.setItemText(11, _translate("MainWindow", "Chaotic Neutral", None))
        self.combobox_alignmentofnpc.setItemText(12, _translate("MainWindow", "Chaotic Evil", None))
        self.label_classofnpc.setText(_translate("MainWindow", "Class :", None))
        self.combobox_classofnpc.setItemText(0, _translate("MainWindow", "Any", None))
        self.combobox_classofnpc.setItemText(1, _translate("MainWindow", "Warrior", None))
        self.combobox_classofnpc.setItemText(2, _translate("MainWindow", "Wizard", None))
        self.combobox_classofnpc.setItemText(3, _translate("MainWindow", "Thief", None))
        self.combobox_classofnpc.setItemText(4, _translate("MainWindow", "Cleric", None))
        self.label_levelofnpc.setText(_translate("MainWindow", "Level :", None))
        self.label_level_number.setText(_translate("MainWindow", "1", None))
        self.label_statsofnpc.setText(_translate("MainWindow", "Stats :", None))
        self.combobox_statsofnpc.setItemText(0, _translate("MainWindow", "Best 3 of 5d6", None))
        self.combobox_statsofnpc.setItemText(1, _translate("MainWindow", "Low", None))
        self.combobox_statsofnpc.setItemText(2, _translate("MainWindow", "Average", None))
        self.combobox_statsofnpc.setItemText(3, _translate("MainWindow", "High", None))
        self.combobox_statsofnpc.setItemText(4, _translate("MainWindow", "Hero", None))
        self.create_campain_tabs.setTabText(self.create_campain_tabs.indexOf(self.npc_generator_tab), _translate("MainWindow", "NPC Generator", None))
        self.create_campain_tabs.setTabText(self.create_campain_tabs.indexOf(self.background_tab), _translate("MainWindow", "Background", None))
        self.dock_client.setWindowTitle(_translate("MainWindow", "Play Dungeons & Dragons", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Map Viewer", None))
        self.groupBox.setTitle(_translate("MainWindow", "Dice Rolls", None))
        self.label_32.setText(_translate("MainWindow", "Result :", None))
        self.label_27.setText(_translate("MainWindow", "_", None))
        self.pushButton_2.setText(_translate("MainWindow", "d6", None))
        self.pushButton_4.setText(_translate("MainWindow", "d10", None))
        self.pushButton_5.setText(_translate("MainWindow", "d12", None))
        self.label_4.setText(_translate("MainWindow", "Sides :", None))
        self.pushButton_3.setText(_translate("MainWindow", "d8", None))
        self.pushButton.setText(_translate("MainWindow", "d4", None))
        self.label_2.setText(_translate("MainWindow", "Number :", None))
        self.label_3.setText(_translate("MainWindow", "Modifier :", None))
        self.pushButton_6.setText(_translate("MainWindow", "d20", None))
        self.pushButton_7.setText(_translate("MainWindow", "d%", None))
        self.pushButton_8.setText(_translate("MainWindow", "d?", None))
        self.checkBox.setText(_translate("MainWindow", "Hide Roll", None))
        self.label_5.setText(_translate("MainWindow", "Player Name :", None))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Player\'s Name", None))
        self.label_6.setText(_translate("MainWindow", "Character Name :", None))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "Character Name", None))
        self.label_7.setText(_translate("MainWindow", "DM Name :", None))
        self.lineEdit_3.setPlaceholderText(_translate("MainWindow", "Dungeon Master\'s Name", None))
        self.toolbutton_charactersheet_options.setText(_translate("MainWindow", "...", None))
        self.label.setText(_translate("MainWindow", "HP :", None))
        self.label_19.setText(_translate("MainWindow", "SPELLS :", None))
        self.label_18.setText(_translate("MainWindow", "DRAGON :", None))
        self.label_17.setText(_translate("MainWindow", "PARALYSIS :", None))
        self.label_12.setText(_translate("MainWindow", "CHA :", None))
        self.label_9.setText(_translate("MainWindow", "INT :", None))
        self.label_13.setText(_translate("MainWindow", "DEX :", None))
        self.label_10.setText(_translate("MainWindow", "WIS :", None))
        self.label_11.setText(_translate("MainWindow", "CON :", None))
        self.lineEdit_6.setPlaceholderText(_translate("MainWindow", "3-18", None))
        self.label_16.setText(_translate("MainWindow", "WANDS :", None))
        self.lineEdit_9.setPlaceholderText(_translate("MainWindow", "3-18", None))
        self.lineEdit_8.setPlaceholderText(_translate("MainWindow", "3-18", None))
        self.label_8.setText(_translate("MainWindow", "STR :", None))
        self.label_15.setText(_translate("MainWindow", "POISON :", None))
        self.label_14.setText(_translate("MainWindow", "SAVES :", None))
        self.lineEdit_4.setPlaceholderText(_translate("MainWindow", "3-18", None))
        self.lineEdit_7.setPlaceholderText(_translate("MainWindow", "3-18", None))
        self.lineEdit_5.setPlaceholderText(_translate("MainWindow", "3-18", None))
        self.label_20.setText(_translate("MainWindow", "AC :", None))
        self.label_21.setText(_translate("MainWindow", "Alignment :", None))
        self.comboBox.setItemText(0, _translate("MainWindow", "Lawful Good", None))
        self.comboBox.setItemText(1, _translate("MainWindow", "Lawful Neutral", None))
        self.comboBox.setItemText(2, _translate("MainWindow", "Lawful Evil", None))
        self.comboBox.setItemText(3, _translate("MainWindow", "Neutral Good", None))
        self.comboBox.setItemText(4, _translate("MainWindow", "Neutral Neutral", None))
        self.comboBox.setItemText(5, _translate("MainWindow", "Neutral Evil", None))
        self.comboBox.setItemText(6, _translate("MainWindow", "Chaotic Good", None))
        self.comboBox.setItemText(7, _translate("MainWindow", "Chaotic Neutral", None))
        self.comboBox.setItemText(8, _translate("MainWindow", "Chaotic Evil", None))
        self.label_22.setText(_translate("MainWindow", "Race :", None))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "Human", None))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "Elf", None))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "Dwarf", None))
        self.comboBox_2.setItemText(3, _translate("MainWindow", "Halfelin", None))
        self.comboBox_2.setItemText(4, _translate("MainWindow", "Ork", None))
        self.label_23.setText(_translate("MainWindow", "Class :", None))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "Warrior", None))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "Wizard", None))
        self.comboBox_3.setItemText(2, _translate("MainWindow", "Cleric", None))
        self.comboBox_3.setItemText(3, _translate("MainWindow", "Thief", None))
        self.label_25.setText(_translate("MainWindow", "Level :", None))
        self.label_26.setText(_translate("MainWindow", "1", None))
        self.label_24.setText(_translate("MainWindow", "INVENTORY & TREASURES :", None))
        self.label_28.setText(_translate("MainWindow", "Add XP :", None))
        self.lineEdit_15.setPlaceholderText(_translate("MainWindow", "Press Enter to Add XP. Bonus is automatically calculated.", None))
        self.label_29.setText(_translate("MainWindow", "Bonus XP :", None))
        self.label_30.setText(_translate("MainWindow", "0", None))
        self.label_31.setText(_translate("MainWindow", "%", None))
        self.tab_character_sheets.setTabText(self.tab_character_sheets.indexOf(self.character_sheet_1), _translate("MainWindow", "%s \'s character sheet", None))
        self.actionNew_Campain.setText(_translate("MainWindow", "New Campain", None))
        self.actionSave_Campain.setText(_translate("MainWindow", "Save Campain", None))
        self.actionLoad_Campain.setText(_translate("MainWindow", "Load Campain", None))
        self.actionQuit.setText(_translate("MainWindow", "Quit", None))
        self.actionHost_Game.setText(_translate("MainWindow", "Host Game", None))
        self.actionConnect_to.setText(_translate("MainWindow", "Connect to...", None))
        self.actionHelp.setText(_translate("MainWindow", "Help", None))
        self.actionAbout.setText(_translate("MainWindow", "About", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

