# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI\main_window.ui'
#
# Created: Wed Aug  5 10:28:48 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(826, 626)
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 826, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuConnect = QtGui.QMenu(self.menubar)
        self.menuConnect.setObjectName(_fromUtf8("menuConnect"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.dock_campain = QtGui.QDockWidget(MainWindow)
        self.dock_campain.setFloating(False)
        self.dock_campain.setObjectName(_fromUtf8("dock_campain"))
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.gridLayout_2 = QtGui.QGridLayout(self.dockWidgetContents)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.create_campain_tabs = QtGui.QTabWidget(self.dockWidgetContents)
        self.create_campain_tabs.setObjectName(_fromUtf8("create_campain_tabs"))
        self.map_designer_tab = QtGui.QWidget()
        self.map_designer_tab.setObjectName(_fromUtf8("map_designer_tab"))
        self.gridLayout_6 = QtGui.QGridLayout(self.map_designer_tab)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.widget_4 = QtGui.QWidget(self.map_designer_tab)
        self.widget_4.setObjectName(_fromUtf8("widget_4"))
        self.gridLayout_6.addWidget(self.widget_4, 1, 2, 1, 1)
        self.groupBox_3 = QtGui.QGroupBox(self.map_designer_tab)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_9 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.toolbox_tabs = QtGui.QTabWidget(self.groupBox_3)
        self.toolbox_tabs.setTabPosition(QtGui.QTabWidget.East)
        self.toolbox_tabs.setObjectName(_fromUtf8("toolbox_tabs"))
        self.door_tab = QtGui.QWidget()
        self.door_tab.setObjectName(_fromUtf8("door_tab"))
        self.gridLayout_8 = QtGui.QGridLayout(self.door_tab)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.tool_door_secret = QtGui.QRadioButton(self.door_tab)
        self.tool_door_secret.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/images/tiles/door_secret.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tool_door_secret.setIcon(icon)
        self.tool_door_secret.setIconSize(QtCore.QSize(64, 64))
        self.tool_door_secret.setObjectName(_fromUtf8("tool_door_secret"))
        self.gridLayout_8.addWidget(self.tool_door_secret, 1, 1, 1, 1)
        self.tool_door_double = QtGui.QRadioButton(self.door_tab)
        self.tool_door_double.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/images/tiles/door_double.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tool_door_double.setIcon(icon1)
        self.tool_door_double.setIconSize(QtCore.QSize(64, 64))
        self.tool_door_double.setObjectName(_fromUtf8("tool_door_double"))
        self.gridLayout_8.addWidget(self.tool_door_double, 0, 1, 1, 1)
        self.tool_door_concealed = QtGui.QRadioButton(self.door_tab)
        self.tool_door_concealed.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/images/tiles/door_concealed.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tool_door_concealed.setIcon(icon2)
        self.tool_door_concealed.setIconSize(QtCore.QSize(64, 64))
        self.tool_door_concealed.setObjectName(_fromUtf8("tool_door_concealed"))
        self.gridLayout_8.addWidget(self.tool_door_concealed, 3, 1, 1, 1)
        self.tool_door_fake = QtGui.QRadioButton(self.door_tab)
        self.tool_door_fake.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/images/tiles/door_fake.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tool_door_fake.setIcon(icon3)
        self.tool_door_fake.setIconSize(QtCore.QSize(64, 64))
        self.tool_door_fake.setObjectName(_fromUtf8("tool_door_fake"))
        self.gridLayout_8.addWidget(self.tool_door_fake, 2, 0, 1, 1)
        self.tool_door_oneway = QtGui.QRadioButton(self.door_tab)
        self.tool_door_oneway.setText(_fromUtf8(""))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/images/tiles/door_oneway.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tool_door_oneway.setIcon(icon4)
        self.tool_door_oneway.setIconSize(QtCore.QSize(64, 64))
        self.tool_door_oneway.setObjectName(_fromUtf8("tool_door_oneway"))
        self.gridLayout_8.addWidget(self.tool_door_oneway, 2, 1, 1, 1)
        self.tool_door_simple = QtGui.QRadioButton(self.door_tab)
        self.tool_door_simple.setText(_fromUtf8(""))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/images/tiles/door_simple.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tool_door_simple.setIcon(icon5)
        self.tool_door_simple.setIconSize(QtCore.QSize(64, 64))
        self.tool_door_simple.setChecked(True)
        self.tool_door_simple.setObjectName(_fromUtf8("tool_door_simple"))
        self.gridLayout_8.addWidget(self.tool_door_simple, 0, 0, 1, 1)
        self.tool_door_open = QtGui.QRadioButton(self.door_tab)
        self.tool_door_open.setText(_fromUtf8(""))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/images/tiles/door_open.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tool_door_open.setIcon(icon6)
        self.tool_door_open.setIconSize(QtCore.QSize(64, 64))
        self.tool_door_open.setObjectName(_fromUtf8("tool_door_open"))
        self.gridLayout_8.addWidget(self.tool_door_open, 1, 0, 1, 1)
        self.tool_door_rotating = QtGui.QRadioButton(self.door_tab)
        self.tool_door_rotating.setText(_fromUtf8(""))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/images/tiles/door_rotating.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tool_door_rotating.setIcon(icon7)
        self.tool_door_rotating.setIconSize(QtCore.QSize(64, 64))
        self.tool_door_rotating.setObjectName(_fromUtf8("tool_door_rotating"))
        self.gridLayout_8.addWidget(self.tool_door_rotating, 3, 0, 1, 1)
        self.tool_door_secretoneway = QtGui.QRadioButton(self.door_tab)
        self.tool_door_secretoneway.setText(_fromUtf8(""))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/images/tiles/door_secretoneway.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tool_door_secretoneway.setIcon(icon8)
        self.tool_door_secretoneway.setIconSize(QtCore.QSize(64, 64))
        self.tool_door_secretoneway.setObjectName(_fromUtf8("tool_door_secretoneway"))
        self.gridLayout_8.addWidget(self.tool_door_secretoneway, 4, 0, 1, 1)
        self.toolbox_tabs.addTab(self.door_tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.toolbox_tabs.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.toolbox_tabs.addTab(self.tab_3, _fromUtf8(""))
        self.gridLayout_9.addWidget(self.toolbox_tabs, 3, 0, 1, 1)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.toolbox_radio_paper_empty = QtGui.QRadioButton(self.groupBox_3)
        self.toolbox_radio_paper_empty.setObjectName(_fromUtf8("toolbox_radio_paper_empty"))
        self.horizontalLayout_6.addWidget(self.toolbox_radio_paper_empty)
        self.toolbox_radio_paper_square = QtGui.QRadioButton(self.groupBox_3)
        self.toolbox_radio_paper_square.setChecked(True)
        self.toolbox_radio_paper_square.setObjectName(_fromUtf8("toolbox_radio_paper_square"))
        self.horizontalLayout_6.addWidget(self.toolbox_radio_paper_square)
        self.toolbox_radio_paper_hexagonal = QtGui.QRadioButton(self.groupBox_3)
        self.toolbox_radio_paper_hexagonal.setObjectName(_fromUtf8("toolbox_radio_paper_hexagonal"))
        self.horizontalLayout_6.addWidget(self.toolbox_radio_paper_hexagonal)
        self.gridLayout_9.addLayout(self.horizontalLayout_6, 0, 0, 1, 1)
        self.gridLayout_6.addWidget(self.groupBox_3, 0, 1, 1, 1)
        self.graphicsView = QtGui.QGraphicsView(self.map_designer_tab)
        self.graphicsView.setObjectName(_fromUtf8("graphicsView"))
        self.gridLayout_6.addWidget(self.graphicsView, 0, 0, 1, 1)
        self.create_campain_tabs.addTab(self.map_designer_tab, _fromUtf8(""))
        self.random_encounters_tab = QtGui.QWidget()
        self.random_encounters_tab.setObjectName(_fromUtf8("random_encounters_tab"))
        self.gridLayout_3 = QtGui.QGridLayout(self.random_encounters_tab)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_environmentofencounter = QtGui.QLabel(self.random_encounters_tab)
        self.label_environmentofencounter.setObjectName(_fromUtf8("label_environmentofencounter"))
        self.gridLayout_3.addWidget(self.label_environmentofencounter, 0, 0, 1, 1)
        self.group_generatedtable = QtGui.QGroupBox(self.random_encounters_tab)
        self.group_generatedtable.setObjectName(_fromUtf8("group_generatedtable"))
        self.gridLayout_4 = QtGui.QGridLayout(self.group_generatedtable)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.layout_generatedtable = QtGui.QFormLayout()
        self.layout_generatedtable.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.layout_generatedtable.setObjectName(_fromUtf8("layout_generatedtable"))
        self.label_generatedtable_1 = QtGui.QLabel(self.group_generatedtable)
        self.label_generatedtable_1.setObjectName(_fromUtf8("label_generatedtable_1"))
        self.layout_generatedtable.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_generatedtable_1)
        self.label_nameofrolledmonster_1 = QtGui.QLabel(self.group_generatedtable)
        self.label_nameofrolledmonster_1.setObjectName(_fromUtf8("label_nameofrolledmonster_1"))
        self.layout_generatedtable.setWidget(0, QtGui.QFormLayout.FieldRole, self.label_nameofrolledmonster_1)
        self.label_generatedtable_2 = QtGui.QLabel(self.group_generatedtable)
        self.label_generatedtable_2.setObjectName(_fromUtf8("label_generatedtable_2"))
        self.layout_generatedtable.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_generatedtable_2)
        self.label_nameofrolledmonster_2 = QtGui.QLabel(self.group_generatedtable)
        self.label_nameofrolledmonster_2.setObjectName(_fromUtf8("label_nameofrolledmonster_2"))
        self.layout_generatedtable.setWidget(1, QtGui.QFormLayout.FieldRole, self.label_nameofrolledmonster_2)
        self.label_generatedtable_3 = QtGui.QLabel(self.group_generatedtable)
        self.label_generatedtable_3.setObjectName(_fromUtf8("label_generatedtable_3"))
        self.layout_generatedtable.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_generatedtable_3)
        self.label_nameofrolledmonster_3 = QtGui.QLabel(self.group_generatedtable)
        self.label_nameofrolledmonster_3.setObjectName(_fromUtf8("label_nameofrolledmonster_3"))
        self.layout_generatedtable.setWidget(2, QtGui.QFormLayout.FieldRole, self.label_nameofrolledmonster_3)
        self.label_generatedtable_4 = QtGui.QLabel(self.group_generatedtable)
        self.label_generatedtable_4.setObjectName(_fromUtf8("label_generatedtable_4"))
        self.layout_generatedtable.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_generatedtable_4)
        self.label_nameofrolledmonster_4 = QtGui.QLabel(self.group_generatedtable)
        self.label_nameofrolledmonster_4.setObjectName(_fromUtf8("label_nameofrolledmonster_4"))
        self.layout_generatedtable.setWidget(3, QtGui.QFormLayout.FieldRole, self.label_nameofrolledmonster_4)
        self.label_generatedtable_5 = QtGui.QLabel(self.group_generatedtable)
        self.label_generatedtable_5.setObjectName(_fromUtf8("label_generatedtable_5"))
        self.layout_generatedtable.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_generatedtable_5)
        self.label_nameofrolledmonster_5 = QtGui.QLabel(self.group_generatedtable)
        self.label_nameofrolledmonster_5.setObjectName(_fromUtf8("label_nameofrolledmonster_5"))
        self.layout_generatedtable.setWidget(4, QtGui.QFormLayout.FieldRole, self.label_nameofrolledmonster_5)
        self.label_generatedtable_6 = QtGui.QLabel(self.group_generatedtable)
        self.label_generatedtable_6.setObjectName(_fromUtf8("label_generatedtable_6"))
        self.layout_generatedtable.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_generatedtable_6)
        self.label_nameofrolledmonster_6 = QtGui.QLabel(self.group_generatedtable)
        self.label_nameofrolledmonster_6.setObjectName(_fromUtf8("label_nameofrolledmonster_6"))
        self.layout_generatedtable.setWidget(5, QtGui.QFormLayout.FieldRole, self.label_nameofrolledmonster_6)
        self.label_generatedtable_7 = QtGui.QLabel(self.group_generatedtable)
        self.label_generatedtable_7.setObjectName(_fromUtf8("label_generatedtable_7"))
        self.layout_generatedtable.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_generatedtable_7)
        self.label_nameofrolledmonster_7 = QtGui.QLabel(self.group_generatedtable)
        self.label_nameofrolledmonster_7.setObjectName(_fromUtf8("label_nameofrolledmonster_7"))
        self.layout_generatedtable.setWidget(6, QtGui.QFormLayout.FieldRole, self.label_nameofrolledmonster_7)
        self.label_generatedtable_8 = QtGui.QLabel(self.group_generatedtable)
        self.label_generatedtable_8.setObjectName(_fromUtf8("label_generatedtable_8"))
        self.layout_generatedtable.setWidget(7, QtGui.QFormLayout.LabelRole, self.label_generatedtable_8)
        self.label_nameofrolledmonster_8 = QtGui.QLabel(self.group_generatedtable)
        self.label_nameofrolledmonster_8.setObjectName(_fromUtf8("label_nameofrolledmonster_8"))
        self.layout_generatedtable.setWidget(7, QtGui.QFormLayout.FieldRole, self.label_nameofrolledmonster_8)
        self.label_generatedtable_9 = QtGui.QLabel(self.group_generatedtable)
        self.label_generatedtable_9.setObjectName(_fromUtf8("label_generatedtable_9"))
        self.layout_generatedtable.setWidget(8, QtGui.QFormLayout.LabelRole, self.label_generatedtable_9)
        self.label_nameofrolledmonster_9 = QtGui.QLabel(self.group_generatedtable)
        self.label_nameofrolledmonster_9.setObjectName(_fromUtf8("label_nameofrolledmonster_9"))
        self.layout_generatedtable.setWidget(8, QtGui.QFormLayout.FieldRole, self.label_nameofrolledmonster_9)
        self.label_generatedtable_10 = QtGui.QLabel(self.group_generatedtable)
        self.label_generatedtable_10.setObjectName(_fromUtf8("label_generatedtable_10"))
        self.layout_generatedtable.setWidget(9, QtGui.QFormLayout.LabelRole, self.label_generatedtable_10)
        self.label_nameofrolledmonster_10 = QtGui.QLabel(self.group_generatedtable)
        self.label_nameofrolledmonster_10.setObjectName(_fromUtf8("label_nameofrolledmonster_10"))
        self.layout_generatedtable.setWidget(9, QtGui.QFormLayout.FieldRole, self.label_nameofrolledmonster_10)
        self.label_generatedtable_11 = QtGui.QLabel(self.group_generatedtable)
        self.label_generatedtable_11.setObjectName(_fromUtf8("label_generatedtable_11"))
        self.layout_generatedtable.setWidget(10, QtGui.QFormLayout.LabelRole, self.label_generatedtable_11)
        self.label_nameofrolledmonster_11 = QtGui.QLabel(self.group_generatedtable)
        self.label_nameofrolledmonster_11.setObjectName(_fromUtf8("label_nameofrolledmonster_11"))
        self.layout_generatedtable.setWidget(10, QtGui.QFormLayout.FieldRole, self.label_nameofrolledmonster_11)
        self.label_generatedtable_12 = QtGui.QLabel(self.group_generatedtable)
        self.label_generatedtable_12.setObjectName(_fromUtf8("label_generatedtable_12"))
        self.layout_generatedtable.setWidget(11, QtGui.QFormLayout.LabelRole, self.label_generatedtable_12)
        self.label_nameofrolledmonster_12 = QtGui.QLabel(self.group_generatedtable)
        self.label_nameofrolledmonster_12.setObjectName(_fromUtf8("label_nameofrolledmonster_12"))
        self.layout_generatedtable.setWidget(11, QtGui.QFormLayout.FieldRole, self.label_nameofrolledmonster_12)
        self.button_rollamonster = QtGui.QPushButton(self.group_generatedtable)
        self.button_rollamonster.setObjectName(_fromUtf8("button_rollamonster"))
        self.layout_generatedtable.setWidget(12, QtGui.QFormLayout.LabelRole, self.button_rollamonster)
        self.button_rollatable = QtGui.QPushButton(self.group_generatedtable)
        self.button_rollatable.setObjectName(_fromUtf8("button_rollatable"))
        self.layout_generatedtable.setWidget(12, QtGui.QFormLayout.FieldRole, self.button_rollatable)
        self.gridLayout_4.addLayout(self.layout_generatedtable, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.group_generatedtable, 4, 0, 3, 1)
        self.group_statsofrolledmonster = QtGui.QGroupBox(self.random_encounters_tab)
        self.group_statsofrolledmonster.setObjectName(_fromUtf8("group_statsofrolledmonster"))
        self.gridLayout_10 = QtGui.QGridLayout(self.group_statsofrolledmonster)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.label_statsofrolledmonster_treasurevalue = QtGui.QLabel(self.group_statsofrolledmonster)
        self.label_statsofrolledmonster_treasurevalue.setObjectName(_fromUtf8("label_statsofrolledmonster_treasurevalue"))
        self.gridLayout_10.addWidget(self.label_statsofrolledmonster_treasurevalue, 7, 0, 1, 1)
        self.monster_xp_value = QtGui.QLabel(self.group_statsofrolledmonster)
        self.monster_xp_value.setObjectName(_fromUtf8("monster_xp_value"))
        self.gridLayout_10.addWidget(self.monster_xp_value, 9, 1, 1, 1)
        self.label_statsofrolledmonster_hp = QtGui.QLabel(self.group_statsofrolledmonster)
        self.label_statsofrolledmonster_hp.setObjectName(_fromUtf8("label_statsofrolledmonster_hp"))
        self.gridLayout_10.addWidget(self.label_statsofrolledmonster_hp, 0, 0, 1, 1)
        self.monster_ac_value = QtGui.QLabel(self.group_statsofrolledmonster)
        self.monster_ac_value.setObjectName(_fromUtf8("monster_ac_value"))
        self.gridLayout_10.addWidget(self.monster_ac_value, 1, 1, 1, 1)
        self.label_statsofrolledmonster_xpvalue = QtGui.QLabel(self.group_statsofrolledmonster)
        self.label_statsofrolledmonster_xpvalue.setObjectName(_fromUtf8("label_statsofrolledmonster_xpvalue"))
        self.gridLayout_10.addWidget(self.label_statsofrolledmonster_xpvalue, 9, 0, 1, 1)
        self.monster_alignment_value = QtGui.QLabel(self.group_statsofrolledmonster)
        self.monster_alignment_value.setObjectName(_fromUtf8("monster_alignment_value"))
        self.gridLayout_10.addWidget(self.monster_alignment_value, 8, 1, 1, 1)
        self.label_statsofrolledmonster_ac = QtGui.QLabel(self.group_statsofrolledmonster)
        self.label_statsofrolledmonster_ac.setObjectName(_fromUtf8("label_statsofrolledmonster_ac"))
        self.gridLayout_10.addWidget(self.label_statsofrolledmonster_ac, 1, 0, 1, 1)
        self.monster_moral_value = QtGui.QLabel(self.group_statsofrolledmonster)
        self.monster_moral_value.setObjectName(_fromUtf8("monster_moral_value"))
        self.gridLayout_10.addWidget(self.monster_moral_value, 5, 1, 1, 1)
        self.monster_attack_value = QtGui.QLabel(self.group_statsofrolledmonster)
        self.monster_attack_value.setObjectName(_fromUtf8("monster_attack_value"))
        self.gridLayout_10.addWidget(self.monster_attack_value, 3, 1, 1, 1)
        self.label_statsofrolledmonster_moral = QtGui.QLabel(self.group_statsofrolledmonster)
        self.label_statsofrolledmonster_moral.setObjectName(_fromUtf8("label_statsofrolledmonster_moral"))
        self.gridLayout_10.addWidget(self.label_statsofrolledmonster_moral, 5, 0, 1, 1)
        self.label_statsofrolledmonster_attacks = QtGui.QLabel(self.group_statsofrolledmonster)
        self.label_statsofrolledmonster_attacks.setObjectName(_fromUtf8("label_statsofrolledmonster_attacks"))
        self.gridLayout_10.addWidget(self.label_statsofrolledmonster_attacks, 3, 0, 1, 1)
        self.monster_movement_value = QtGui.QLabel(self.group_statsofrolledmonster)
        self.monster_movement_value.setObjectName(_fromUtf8("monster_movement_value"))
        self.gridLayout_10.addWidget(self.monster_movement_value, 2, 1, 1, 1)
        self.label_statsofrolledmonster_movement = QtGui.QLabel(self.group_statsofrolledmonster)
        self.label_statsofrolledmonster_movement.setObjectName(_fromUtf8("label_statsofrolledmonster_movement"))
        self.gridLayout_10.addWidget(self.label_statsofrolledmonster_movement, 2, 0, 1, 1)
        self.label_statsofrolledmonster_alignment = QtGui.QLabel(self.group_statsofrolledmonster)
        self.label_statsofrolledmonster_alignment.setObjectName(_fromUtf8("label_statsofrolledmonster_alignment"))
        self.gridLayout_10.addWidget(self.label_statsofrolledmonster_alignment, 8, 0, 1, 1)
        self.monster_damages_value = QtGui.QLabel(self.group_statsofrolledmonster)
        self.monster_damages_value.setObjectName(_fromUtf8("monster_damages_value"))
        self.gridLayout_10.addWidget(self.monster_damages_value, 4, 1, 1, 1)
        self.label_statsofrolledmonster_damages = QtGui.QLabel(self.group_statsofrolledmonster)
        self.label_statsofrolledmonster_damages.setObjectName(_fromUtf8("label_statsofrolledmonster_damages"))
        self.gridLayout_10.addWidget(self.label_statsofrolledmonster_damages, 4, 0, 1, 1)
        self.label_statsofrolledmonster_saves = QtGui.QLabel(self.group_statsofrolledmonster)
        self.label_statsofrolledmonster_saves.setObjectName(_fromUtf8("label_statsofrolledmonster_saves"))
        self.gridLayout_10.addWidget(self.label_statsofrolledmonster_saves, 6, 0, 1, 1)
        self.gridLayout_12 = QtGui.QGridLayout()
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.monster_saves_poison_value = QtGui.QLabel(self.group_statsofrolledmonster)
        self.monster_saves_poison_value.setObjectName(_fromUtf8("monster_saves_poison_value"))
        self.gridLayout_12.addWidget(self.monster_saves_poison_value, 1, 0, 1, 1)
        self.label_monster_saves_poi = QtGui.QLabel(self.group_statsofrolledmonster)
        self.label_monster_saves_poi.setObjectName(_fromUtf8("label_monster_saves_poi"))
        self.gridLayout_12.addWidget(self.label_monster_saves_poi, 0, 0, 1, 1)
        self.label_monster_saves_dra = QtGui.QLabel(self.group_statsofrolledmonster)
        self.label_monster_saves_dra.setObjectName(_fromUtf8("label_monster_saves_dra"))
        self.gridLayout_12.addWidget(self.label_monster_saves_dra, 0, 3, 1, 1)
        self.label_monster_saves_par = QtGui.QLabel(self.group_statsofrolledmonster)
        self.label_monster_saves_par.setObjectName(_fromUtf8("label_monster_saves_par"))
        self.gridLayout_12.addWidget(self.label_monster_saves_par, 0, 2, 1, 1)
        self.label_monster_saves_wan = QtGui.QLabel(self.group_statsofrolledmonster)
        self.label_monster_saves_wan.setObjectName(_fromUtf8("label_monster_saves_wan"))
        self.gridLayout_12.addWidget(self.label_monster_saves_wan, 0, 1, 1, 1)
        self.label_monster_saves_spe = QtGui.QLabel(self.group_statsofrolledmonster)
        self.label_monster_saves_spe.setObjectName(_fromUtf8("label_monster_saves_spe"))
        self.gridLayout_12.addWidget(self.label_monster_saves_spe, 0, 4, 1, 1)
        self.monster_saves_wands_value = QtGui.QLabel(self.group_statsofrolledmonster)
        self.monster_saves_wands_value.setObjectName(_fromUtf8("monster_saves_wands_value"))
        self.gridLayout_12.addWidget(self.monster_saves_wands_value, 1, 1, 1, 1)
        self.monster_saves_paralysis_value = QtGui.QLabel(self.group_statsofrolledmonster)
        self.monster_saves_paralysis_value.setObjectName(_fromUtf8("monster_saves_paralysis_value"))
        self.gridLayout_12.addWidget(self.monster_saves_paralysis_value, 1, 2, 1, 1)
        self.monster_saves_dragonbreath_value = QtGui.QLabel(self.group_statsofrolledmonster)
        self.monster_saves_dragonbreath_value.setObjectName(_fromUtf8("monster_saves_dragonbreath_value"))
        self.gridLayout_12.addWidget(self.monster_saves_dragonbreath_value, 1, 3, 1, 1)
        self.monster_saves_spells_value = QtGui.QLabel(self.group_statsofrolledmonster)
        self.monster_saves_spells_value.setObjectName(_fromUtf8("monster_saves_spells_value"))
        self.gridLayout_12.addWidget(self.monster_saves_spells_value, 1, 4, 1, 1)
        self.gridLayout_10.addLayout(self.gridLayout_12, 6, 1, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.progressbar_healthorolledmonster = QtGui.QProgressBar(self.group_statsofrolledmonster)
        self.progressbar_healthorolledmonster.setProperty("value", 100)
        self.progressbar_healthorolledmonster.setObjectName(_fromUtf8("progressbar_healthorolledmonster"))
        self.horizontalLayout_4.addWidget(self.progressbar_healthorolledmonster)
        self.spin_damagetoinflict = QtGui.QSpinBox(self.group_statsofrolledmonster)
        self.spin_damagetoinflict.setObjectName(_fromUtf8("spin_damagetoinflict"))
        self.horizontalLayout_4.addWidget(self.spin_damagetoinflict)
        self.button_inflictdamage = QtGui.QPushButton(self.group_statsofrolledmonster)
        self.button_inflictdamage.setObjectName(_fromUtf8("button_inflictdamage"))
        self.horizontalLayout_4.addWidget(self.button_inflictdamage)
        self.gridLayout_10.addLayout(self.horizontalLayout_4, 0, 1, 1, 1)
        self.monster_treasure_value = QtGui.QLabel(self.group_statsofrolledmonster)
        self.monster_treasure_value.setObjectName(_fromUtf8("monster_treasure_value"))
        self.gridLayout_10.addWidget(self.monster_treasure_value, 7, 1, 1, 1)
        self.gridLayout_3.addWidget(self.group_statsofrolledmonster, 4, 1, 3, 1)
        self.combo_environmentofencounter = QtGui.QComboBox(self.random_encounters_tab)
        self.combo_environmentofencounter.setObjectName(_fromUtf8("combo_environmentofencounter"))
        self.combo_environmentofencounter.addItem(_fromUtf8(""))
        self.combo_environmentofencounter.addItem(_fromUtf8(""))
        self.combo_environmentofencounter.addItem(_fromUtf8(""))
        self.combo_environmentofencounter.addItem(_fromUtf8(""))
        self.combo_environmentofencounter.addItem(_fromUtf8(""))
        self.combo_environmentofencounter.addItem(_fromUtf8(""))
        self.combo_environmentofencounter.addItem(_fromUtf8(""))
        self.combo_environmentofencounter.addItem(_fromUtf8(""))
        self.combo_environmentofencounter.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.combo_environmentofencounter, 0, 1, 1, 1)
        self.label_chanceofencounter = QtGui.QLabel(self.random_encounters_tab)
        self.label_chanceofencounter.setObjectName(_fromUtf8("label_chanceofencounter"))
        self.gridLayout_3.addWidget(self.label_chanceofencounter, 2, 0, 1, 1)
        self.layout_horiz_chancofencounter = QtGui.QHBoxLayout()
        self.layout_horiz_chancofencounter.setObjectName(_fromUtf8("layout_horiz_chancofencounter"))
        self.slider_chanceofencounter = QtGui.QSlider(self.random_encounters_tab)
        self.slider_chanceofencounter.setMaximum(100)
        self.slider_chanceofencounter.setProperty("value", 10)
        self.slider_chanceofencounter.setOrientation(QtCore.Qt.Horizontal)
        self.slider_chanceofencounter.setObjectName(_fromUtf8("slider_chanceofencounter"))
        self.layout_horiz_chancofencounter.addWidget(self.slider_chanceofencounter)
        self.label_display_chanceofencounter = QtGui.QLabel(self.random_encounters_tab)
        self.label_display_chanceofencounter.setObjectName(_fromUtf8("label_display_chanceofencounter"))
        self.layout_horiz_chancofencounter.addWidget(self.label_display_chanceofencounter)
        self.gridLayout_3.addLayout(self.layout_horiz_chancofencounter, 2, 1, 1, 1)
        self.create_campain_tabs.addTab(self.random_encounters_tab, _fromUtf8(""))
        self.monster_reactions_tab = QtGui.QWidget()
        self.monster_reactions_tab.setObjectName(_fromUtf8("monster_reactions_tab"))
        self.gridLayout_13 = QtGui.QGridLayout(self.monster_reactions_tab)
        self.gridLayout_13.setObjectName(_fromUtf8("gridLayout_13"))
        self.groupBox_4 = QtGui.QGroupBox(self.monster_reactions_tab)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.gridLayout_13.addWidget(self.groupBox_4, 0, 0, 1, 1)
        self.groupBox_5 = QtGui.QGroupBox(self.monster_reactions_tab)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.gridLayout_13.addWidget(self.groupBox_5, 0, 1, 1, 1)
        self.create_campain_tabs.addTab(self.monster_reactions_tab, _fromUtf8(""))
        self.treasure_generator_tab = QtGui.QWidget()
        self.treasure_generator_tab.setObjectName(_fromUtf8("treasure_generator_tab"))
        self.gridLayout_14 = QtGui.QGridLayout(self.treasure_generator_tab)
        self.gridLayout_14.setObjectName(_fromUtf8("gridLayout_14"))
        self.widget_7 = QtGui.QWidget(self.treasure_generator_tab)
        self.widget_7.setObjectName(_fromUtf8("widget_7"))
        self.gridLayout_15 = QtGui.QGridLayout(self.widget_7)
        self.gridLayout_15.setMargin(0)
        self.gridLayout_15.setObjectName(_fromUtf8("gridLayout_15"))
        self.comboBox_2 = QtGui.QComboBox(self.widget_7)
        self.comboBox_2.setObjectName(_fromUtf8("comboBox_2"))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.gridLayout_15.addWidget(self.comboBox_2, 0, 1, 1, 1)
        self.label_54 = QtGui.QLabel(self.widget_7)
        self.label_54.setObjectName(_fromUtf8("label_54"))
        self.gridLayout_15.addWidget(self.label_54, 0, 0, 1, 1)
        self.gridLayout_14.addWidget(self.widget_7, 1, 1, 1, 1)
        self.widget_8 = QtGui.QWidget(self.treasure_generator_tab)
        self.widget_8.setObjectName(_fromUtf8("widget_8"))
        self.gridLayout_16 = QtGui.QGridLayout(self.widget_8)
        self.gridLayout_16.setMargin(0)
        self.gridLayout_16.setObjectName(_fromUtf8("gridLayout_16"))
        self.label_57 = QtGui.QLabel(self.widget_8)
        self.label_57.setObjectName(_fromUtf8("label_57"))
        self.gridLayout_16.addWidget(self.label_57, 0, 1, 1, 1)
        self.label_59 = QtGui.QLabel(self.widget_8)
        self.label_59.setObjectName(_fromUtf8("label_59"))
        self.gridLayout_16.addWidget(self.label_59, 0, 3, 1, 1)
        self.label_60 = QtGui.QLabel(self.widget_8)
        self.label_60.setObjectName(_fromUtf8("label_60"))
        self.gridLayout_16.addWidget(self.label_60, 0, 4, 1, 1)
        self.label_55 = QtGui.QLabel(self.widget_8)
        self.label_55.setObjectName(_fromUtf8("label_55"))
        self.gridLayout_16.addWidget(self.label_55, 0, 0, 1, 1)
        self.label_58 = QtGui.QLabel(self.widget_8)
        self.label_58.setObjectName(_fromUtf8("label_58"))
        self.gridLayout_16.addWidget(self.label_58, 0, 2, 1, 1)
        self.lineEdit = QtGui.QLineEdit(self.widget_8)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.gridLayout_16.addWidget(self.lineEdit, 1, 0, 1, 1)
        self.lineEdit_2 = QtGui.QLineEdit(self.widget_8)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.gridLayout_16.addWidget(self.lineEdit_2, 1, 1, 1, 1)
        self.lineEdit_3 = QtGui.QLineEdit(self.widget_8)
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.gridLayout_16.addWidget(self.lineEdit_3, 1, 2, 1, 1)
        self.lineEdit_4 = QtGui.QLineEdit(self.widget_8)
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.gridLayout_16.addWidget(self.lineEdit_4, 1, 3, 1, 1)
        self.lineEdit_5 = QtGui.QLineEdit(self.widget_8)
        self.lineEdit_5.setObjectName(_fromUtf8("lineEdit_5"))
        self.gridLayout_16.addWidget(self.lineEdit_5, 1, 4, 1, 1)
        self.gridLayout_14.addWidget(self.widget_8, 2, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_14.addItem(spacerItem, 4, 1, 1, 1)
        self.widget_9 = QtGui.QWidget(self.treasure_generator_tab)
        self.widget_9.setObjectName(_fromUtf8("widget_9"))
        self.gridLayout_17 = QtGui.QGridLayout(self.widget_9)
        self.gridLayout_17.setMargin(0)
        self.gridLayout_17.setObjectName(_fromUtf8("gridLayout_17"))
        self.label_56 = QtGui.QLabel(self.widget_9)
        self.label_56.setObjectName(_fromUtf8("label_56"))
        self.gridLayout_17.addWidget(self.label_56, 0, 0, 1, 1)
        self.label_62 = QtGui.QLabel(self.widget_9)
        self.label_62.setObjectName(_fromUtf8("label_62"))
        self.gridLayout_17.addWidget(self.label_62, 2, 0, 1, 1)
        self.label_61 = QtGui.QLabel(self.widget_9)
        self.label_61.setObjectName(_fromUtf8("label_61"))
        self.gridLayout_17.addWidget(self.label_61, 1, 0, 1, 1)
        self.textBrowser_2 = QtGui.QTextBrowser(self.widget_9)
        self.textBrowser_2.setObjectName(_fromUtf8("textBrowser_2"))
        self.gridLayout_17.addWidget(self.textBrowser_2, 0, 1, 1, 1)
        self.textBrowser_3 = QtGui.QTextBrowser(self.widget_9)
        self.textBrowser_3.setObjectName(_fromUtf8("textBrowser_3"))
        self.gridLayout_17.addWidget(self.textBrowser_3, 1, 1, 1, 1)
        self.textBrowser_4 = QtGui.QTextBrowser(self.widget_9)
        self.textBrowser_4.setObjectName(_fromUtf8("textBrowser_4"))
        self.gridLayout_17.addWidget(self.textBrowser_4, 2, 1, 1, 1)
        self.gridLayout_14.addWidget(self.widget_9, 3, 1, 1, 1)
        self.create_campain_tabs.addTab(self.treasure_generator_tab, _fromUtf8(""))
        self.disease_generator_tab = QtGui.QWidget()
        self.disease_generator_tab.setObjectName(_fromUtf8("disease_generator_tab"))
        self.create_campain_tabs.addTab(self.disease_generator_tab, _fromUtf8(""))
        self.npc_generator_tab = QtGui.QWidget()
        self.npc_generator_tab.setObjectName(_fromUtf8("npc_generator_tab"))
        self.gridLayout_18 = QtGui.QGridLayout(self.npc_generator_tab)
        self.gridLayout_18.setObjectName(_fromUtf8("gridLayout_18"))
        self.groupBox_6 = QtGui.QGroupBox(self.npc_generator_tab)
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.gridLayout_19 = QtGui.QGridLayout(self.groupBox_6)
        self.gridLayout_19.setObjectName(_fromUtf8("gridLayout_19"))
        self.label_65 = QtGui.QLabel(self.groupBox_6)
        self.label_65.setObjectName(_fromUtf8("label_65"))
        self.gridLayout_19.addWidget(self.label_65, 2, 0, 1, 1)
        self.label_64 = QtGui.QLabel(self.groupBox_6)
        self.label_64.setObjectName(_fromUtf8("label_64"))
        self.gridLayout_19.addWidget(self.label_64, 1, 0, 1, 1)
        self.comboBox_4 = QtGui.QComboBox(self.groupBox_6)
        self.comboBox_4.setObjectName(_fromUtf8("comboBox_4"))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.gridLayout_19.addWidget(self.comboBox_4, 1, 1, 1, 1)
        self.label_63 = QtGui.QLabel(self.groupBox_6)
        self.label_63.setObjectName(_fromUtf8("label_63"))
        self.gridLayout_19.addWidget(self.label_63, 0, 0, 1, 1)
        self.comboBox_5 = QtGui.QComboBox(self.groupBox_6)
        self.comboBox_5.setObjectName(_fromUtf8("comboBox_5"))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.gridLayout_19.addWidget(self.comboBox_5, 2, 1, 1, 1)
        self.comboBox_3 = QtGui.QComboBox(self.groupBox_6)
        self.comboBox_3.setObjectName(_fromUtf8("comboBox_3"))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.gridLayout_19.addWidget(self.comboBox_3, 0, 1, 1, 1)
        self.label_66 = QtGui.QLabel(self.groupBox_6)
        self.label_66.setObjectName(_fromUtf8("label_66"))
        self.gridLayout_19.addWidget(self.label_66, 0, 2, 1, 1)
        self.comboBox_6 = QtGui.QComboBox(self.groupBox_6)
        self.comboBox_6.setObjectName(_fromUtf8("comboBox_6"))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.gridLayout_19.addWidget(self.comboBox_6, 0, 3, 1, 1)
        self.label_67 = QtGui.QLabel(self.groupBox_6)
        self.label_67.setObjectName(_fromUtf8("label_67"))
        self.gridLayout_19.addWidget(self.label_67, 1, 2, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.horizontalSlider = QtGui.QSlider(self.groupBox_6)
        self.horizontalSlider.setMinimum(1)
        self.horizontalSlider.setMaximum(20)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName(_fromUtf8("horizontalSlider"))
        self.horizontalLayout_2.addWidget(self.horizontalSlider)
        self.label_68 = QtGui.QLabel(self.groupBox_6)
        self.label_68.setObjectName(_fromUtf8("label_68"))
        self.horizontalLayout_2.addWidget(self.label_68)
        self.gridLayout_19.addLayout(self.horizontalLayout_2, 1, 3, 1, 1)
        self.label_69 = QtGui.QLabel(self.groupBox_6)
        self.label_69.setObjectName(_fromUtf8("label_69"))
        self.gridLayout_19.addWidget(self.label_69, 2, 2, 1, 1)
        self.comboBox_7 = QtGui.QComboBox(self.groupBox_6)
        self.comboBox_7.setObjectName(_fromUtf8("comboBox_7"))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.gridLayout_19.addWidget(self.comboBox_7, 2, 3, 1, 1)
        self.gridLayout_18.addWidget(self.groupBox_6, 0, 0, 1, 1)
        self.textBrowser_5 = QtGui.QTextBrowser(self.npc_generator_tab)
        self.textBrowser_5.setObjectName(_fromUtf8("textBrowser_5"))
        self.gridLayout_18.addWidget(self.textBrowser_5, 1, 0, 1, 1)
        self.create_campain_tabs.addTab(self.npc_generator_tab, _fromUtf8(""))
        self.background_tab = QtGui.QWidget()
        self.background_tab.setObjectName(_fromUtf8("background_tab"))
        self.gridLayout = QtGui.QGridLayout(self.background_tab)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.plainTextEdit = QtGui.QPlainTextEdit(self.background_tab)
        self.plainTextEdit.setObjectName(_fromUtf8("plainTextEdit"))
        self.gridLayout.addWidget(self.plainTextEdit, 3, 0, 1, 1)
        self.verticalScrollBar = QtGui.QScrollBar(self.background_tab)
        self.verticalScrollBar.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar.setObjectName(_fromUtf8("verticalScrollBar"))
        self.gridLayout.addWidget(self.verticalScrollBar, 3, 1, 1, 1)
        self.fontComboBox = QtGui.QFontComboBox(self.background_tab)
        self.fontComboBox.setObjectName(_fromUtf8("fontComboBox"))
        self.gridLayout.addWidget(self.fontComboBox, 0, 0, 1, 1)
        self.create_campain_tabs.addTab(self.background_tab, _fromUtf8(""))
        self.gridLayout_2.addWidget(self.create_campain_tabs, 0, 0, 1, 1)
        self.dock_campain.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(4), self.dock_campain)
        self.actionNew_Campain = QtGui.QAction(MainWindow)
        self.actionNew_Campain.setObjectName(_fromUtf8("actionNew_Campain"))
        self.actionSave_Campain = QtGui.QAction(MainWindow)
        self.actionSave_Campain.setObjectName(_fromUtf8("actionSave_Campain"))
        self.actionLoad_Campain = QtGui.QAction(MainWindow)
        self.actionLoad_Campain.setObjectName(_fromUtf8("actionLoad_Campain"))
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionHost_Game = QtGui.QAction(MainWindow)
        self.actionHost_Game.setObjectName(_fromUtf8("actionHost_Game"))
        self.actionConnect_to = QtGui.QAction(MainWindow)
        self.actionConnect_to.setObjectName(_fromUtf8("actionConnect_to"))
        self.actionHelp = QtGui.QAction(MainWindow)
        self.actionHelp.setObjectName(_fromUtf8("actionHelp"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.menuFile.addAction(self.actionNew_Campain)
        self.menuFile.addAction(self.actionSave_Campain)
        self.menuFile.addAction(self.actionLoad_Campain)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuConnect.addAction(self.actionHost_Game)
        self.menuConnect.addSeparator()
        self.menuConnect.addAction(self.actionConnect_to)
        self.menuHelp.addAction(self.actionHelp)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuConnect.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.create_campain_tabs.setCurrentIndex(0)
        self.toolbox_tabs.setCurrentIndex(0)
        QtCore.QObject.connect(self.actionNew_Campain, QtCore.SIGNAL(_fromUtf8("activated()")), self.dock_campain.show)
        QtCore.QObject.connect(self.horizontalSlider, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.label_68.setNum)
        QtCore.QObject.connect(self.slider_chanceofencounter, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.label_display_chanceofencounter.setNum)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Dungeon and Dragons", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuConnect.setTitle(_translate("MainWindow", "Connect", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "ToolBox", None))
        self.toolbox_tabs.setTabText(self.toolbox_tabs.indexOf(self.door_tab), _translate("MainWindow", "Doors", None))
        self.toolbox_tabs.setTabText(self.toolbox_tabs.indexOf(self.tab_2), _translate("MainWindow", "Page", None))
        self.toolbox_tabs.setTabText(self.toolbox_tabs.indexOf(self.tab_3), _translate("MainWindow", "Page", None))
        self.toolbox_radio_paper_empty.setText(_translate("MainWindow", "Empty", None))
        self.toolbox_radio_paper_square.setText(_translate("MainWindow", "Squares", None))
        self.toolbox_radio_paper_hexagonal.setText(_translate("MainWindow", "Hexagonal", None))
        self.create_campain_tabs.setTabText(self.create_campain_tabs.indexOf(self.map_designer_tab), _translate("MainWindow", "Map Designer", None))
        self.label_environmentofencounter.setText(_translate("MainWindow", "Environement of Encounter", None))
        self.group_generatedtable.setTitle(_translate("MainWindow", "Generated Table", None))
        self.label_generatedtable_1.setText(_translate("MainWindow", "1 :", None))
        self.label_nameofrolledmonster_1.setText(_translate("MainWindow", "_", None))
        self.label_generatedtable_2.setText(_translate("MainWindow", "2 :", None))
        self.label_nameofrolledmonster_2.setText(_translate("MainWindow", "_", None))
        self.label_generatedtable_3.setText(_translate("MainWindow", "3 :", None))
        self.label_nameofrolledmonster_3.setText(_translate("MainWindow", "_", None))
        self.label_generatedtable_4.setText(_translate("MainWindow", "4 :", None))
        self.label_nameofrolledmonster_4.setText(_translate("MainWindow", "_", None))
        self.label_generatedtable_5.setText(_translate("MainWindow", "5 :", None))
        self.label_nameofrolledmonster_5.setText(_translate("MainWindow", "_", None))
        self.label_generatedtable_6.setText(_translate("MainWindow", "6 :", None))
        self.label_nameofrolledmonster_6.setText(_translate("MainWindow", "_", None))
        self.label_generatedtable_7.setText(_translate("MainWindow", "7 :", None))
        self.label_nameofrolledmonster_7.setText(_translate("MainWindow", "_", None))
        self.label_generatedtable_8.setText(_translate("MainWindow", "8 :", None))
        self.label_nameofrolledmonster_8.setText(_translate("MainWindow", "_", None))
        self.label_generatedtable_9.setText(_translate("MainWindow", "9 :", None))
        self.label_nameofrolledmonster_9.setText(_translate("MainWindow", "_", None))
        self.label_generatedtable_10.setText(_translate("MainWindow", "10 :", None))
        self.label_nameofrolledmonster_10.setText(_translate("MainWindow", "_", None))
        self.label_generatedtable_11.setText(_translate("MainWindow", "11 :", None))
        self.label_nameofrolledmonster_11.setText(_translate("MainWindow", "_", None))
        self.label_generatedtable_12.setText(_translate("MainWindow", "12 :", None))
        self.label_nameofrolledmonster_12.setText(_translate("MainWindow", "_", None))
        self.button_rollamonster.setText(_translate("MainWindow", "Roll a Monster", None))
        self.button_rollatable.setText(_translate("MainWindow", "Roll a Table", None))
        self.group_statsofrolledmonster.setTitle(_translate("MainWindow", "Stats of the Rolled Monster", None))
        self.label_statsofrolledmonster_treasurevalue.setText(_translate("MainWindow", "Treasure Value :", None))
        self.monster_xp_value.setText(_translate("MainWindow", "_", None))
        self.label_statsofrolledmonster_hp.setText(_translate("MainWindow", "HP :", None))
        self.monster_ac_value.setText(_translate("MainWindow", "_", None))
        self.label_statsofrolledmonster_xpvalue.setText(_translate("MainWindow", "XP Value :", None))
        self.monster_alignment_value.setText(_translate("MainWindow", "_", None))
        self.label_statsofrolledmonster_ac.setText(_translate("MainWindow", "AC :", None))
        self.monster_moral_value.setText(_translate("MainWindow", "_", None))
        self.monster_attack_value.setText(_translate("MainWindow", "_", None))
        self.label_statsofrolledmonster_moral.setText(_translate("MainWindow", "Moral :", None))
        self.label_statsofrolledmonster_attacks.setText(_translate("MainWindow", "Attacks :", None))
        self.monster_movement_value.setText(_translate("MainWindow", "_", None))
        self.label_statsofrolledmonster_movement.setText(_translate("MainWindow", "Movement", None))
        self.label_statsofrolledmonster_alignment.setText(_translate("MainWindow", "Alignment :", None))
        self.monster_damages_value.setText(_translate("MainWindow", "_", None))
        self.label_statsofrolledmonster_damages.setText(_translate("MainWindow", "Damages :", None))
        self.label_statsofrolledmonster_saves.setText(_translate("MainWindow", "Saves :", None))
        self.monster_saves_poison_value.setText(_translate("MainWindow", "_", None))
        self.label_monster_saves_poi.setText(_translate("MainWindow", "Poison/Deathray", None))
        self.label_monster_saves_dra.setText(_translate("MainWindow", "Dragon Breath", None))
        self.label_monster_saves_par.setText(_translate("MainWindow", "Paralysis", None))
        self.label_monster_saves_wan.setText(_translate("MainWindow", "Wands", None))
        self.label_monster_saves_spe.setText(_translate("MainWindow", "Spells", None))
        self.monster_saves_wands_value.setText(_translate("MainWindow", "_", None))
        self.monster_saves_paralysis_value.setText(_translate("MainWindow", "_", None))
        self.monster_saves_dragonbreath_value.setText(_translate("MainWindow", "_", None))
        self.monster_saves_spells_value.setText(_translate("MainWindow", "_", None))
        self.button_inflictdamage.setText(_translate("MainWindow", "Hit", None))
        self.monster_treasure_value.setText(_translate("MainWindow", "_", None))
        self.combo_environmentofencounter.setItemText(0, _translate("MainWindow", "Forest", None))
        self.combo_environmentofencounter.setItemText(1, _translate("MainWindow", "Swamp", None))
        self.combo_environmentofencounter.setItemText(2, _translate("MainWindow", "Mountain", None))
        self.combo_environmentofencounter.setItemText(3, _translate("MainWindow", "Desert (Warm)", None))
        self.combo_environmentofencounter.setItemText(4, _translate("MainWindow", "Desert (Cold)", None))
        self.combo_environmentofencounter.setItemText(5, _translate("MainWindow", "City", None))
        self.combo_environmentofencounter.setItemText(6, _translate("MainWindow", "Dungeon", None))
        self.combo_environmentofencounter.setItemText(7, _translate("MainWindow", "Lair (Insect)", None))
        self.combo_environmentofencounter.setItemText(8, _translate("MainWindow", "Lair (Gobelin)", None))
        self.label_chanceofencounter.setText(_translate("MainWindow", "Chance of Encounter", None))
        self.label_display_chanceofencounter.setText(_translate("MainWindow", "10", None))
        self.create_campain_tabs.setTabText(self.create_campain_tabs.indexOf(self.random_encounters_tab), _translate("MainWindow", "Random Encounters", None))
        self.groupBox_4.setTitle(_translate("MainWindow", "Reactions", None))
        self.groupBox_5.setTitle(_translate("MainWindow", "Moral", None))
        self.create_campain_tabs.setTabText(self.create_campain_tabs.indexOf(self.monster_reactions_tab), _translate("MainWindow", "Monster Reactions", None))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "A", None))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "B", None))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "C", None))
        self.comboBox_2.setItemText(3, _translate("MainWindow", "D", None))
        self.comboBox_2.setItemText(4, _translate("MainWindow", "E", None))
        self.comboBox_2.setItemText(5, _translate("MainWindow", "F", None))
        self.comboBox_2.setItemText(6, _translate("MainWindow", "G", None))
        self.comboBox_2.setItemText(7, _translate("MainWindow", "H", None))
        self.comboBox_2.setItemText(8, _translate("MainWindow", "I", None))
        self.comboBox_2.setItemText(9, _translate("MainWindow", "J", None))
        self.comboBox_2.setItemText(10, _translate("MainWindow", "K", None))
        self.comboBox_2.setItemText(11, _translate("MainWindow", "L", None))
        self.comboBox_2.setItemText(12, _translate("MainWindow", "M", None))
        self.comboBox_2.setItemText(13, _translate("MainWindow", "N", None))
        self.comboBox_2.setItemText(14, _translate("MainWindow", "O", None))
        self.comboBox_2.setItemText(15, _translate("MainWindow", "P", None))
        self.comboBox_2.setItemText(16, _translate("MainWindow", "Q", None))
        self.comboBox_2.setItemText(17, _translate("MainWindow", "R", None))
        self.comboBox_2.setItemText(18, _translate("MainWindow", "S", None))
        self.comboBox_2.setItemText(19, _translate("MainWindow", "T", None))
        self.comboBox_2.setItemText(20, _translate("MainWindow", "U", None))
        self.comboBox_2.setItemText(21, _translate("MainWindow", "V", None))
        self.label_54.setText(_translate("MainWindow", "Treasure Type :", None))
        self.label_57.setText(_translate("MainWindow", "Silver Coins", None))
        self.label_59.setText(_translate("MainWindow", "Golden Coins", None))
        self.label_60.setText(_translate("MainWindow", "Platinum Coins", None))
        self.label_55.setText(_translate("MainWindow", "Copper Coins", None))
        self.label_58.setText(_translate("MainWindow", "Electrum Coins", None))
        self.label_56.setText(_translate("MainWindow", "Gems", None))
        self.label_62.setText(_translate("MainWindow", "Magic Items", None))
        self.label_61.setText(_translate("MainWindow", "Jewels", None))
        self.create_campain_tabs.setTabText(self.create_campain_tabs.indexOf(self.treasure_generator_tab), _translate("MainWindow", "Treasure Generator", None))
        self.create_campain_tabs.setTabText(self.create_campain_tabs.indexOf(self.disease_generator_tab), _translate("MainWindow", "Disease Generator", None))
        self.groupBox_6.setTitle(_translate("MainWindow", "Parameters of generation", None))
        self.label_65.setText(_translate("MainWindow", "Race :", None))
        self.label_64.setText(_translate("MainWindow", "Gender :", None))
        self.comboBox_4.setItemText(0, _translate("MainWindow", "Any", None))
        self.comboBox_4.setItemText(1, _translate("MainWindow", "Male", None))
        self.comboBox_4.setItemText(2, _translate("MainWindow", "Female", None))
        self.label_63.setText(_translate("MainWindow", "Alignment :", None))
        self.comboBox_5.setItemText(0, _translate("MainWindow", "Any", None))
        self.comboBox_5.setItemText(1, _translate("MainWindow", "Human", None))
        self.comboBox_5.setItemText(2, _translate("MainWindow", "Elf", None))
        self.comboBox_5.setItemText(3, _translate("MainWindow", "Dwarf", None))
        self.comboBox_5.setItemText(4, _translate("MainWindow", "Halfelin", None))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "Any", None))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "Any Lawful", None))
        self.comboBox_3.setItemText(2, _translate("MainWindow", "Any Neutral", None))
        self.comboBox_3.setItemText(3, _translate("MainWindow", "Any Chaotic", None))
        self.comboBox_3.setItemText(4, _translate("MainWindow", "Lawful Good", None))
        self.comboBox_3.setItemText(5, _translate("MainWindow", "Lawful Neutral", None))
        self.comboBox_3.setItemText(6, _translate("MainWindow", "Lawful Evil", None))
        self.comboBox_3.setItemText(7, _translate("MainWindow", "Neutral Good", None))
        self.comboBox_3.setItemText(8, _translate("MainWindow", "Neutral Neutral", None))
        self.comboBox_3.setItemText(9, _translate("MainWindow", "Neutral Evil", None))
        self.comboBox_3.setItemText(10, _translate("MainWindow", "Chaotic Good", None))
        self.comboBox_3.setItemText(11, _translate("MainWindow", "Chaotic Neutral", None))
        self.comboBox_3.setItemText(12, _translate("MainWindow", "Chaotic Evil", None))
        self.label_66.setText(_translate("MainWindow", "Class :", None))
        self.comboBox_6.setItemText(0, _translate("MainWindow", "Any", None))
        self.comboBox_6.setItemText(1, _translate("MainWindow", "Warrior", None))
        self.comboBox_6.setItemText(2, _translate("MainWindow", "Wizard", None))
        self.comboBox_6.setItemText(3, _translate("MainWindow", "Thief", None))
        self.comboBox_6.setItemText(4, _translate("MainWindow", "Cleric", None))
        self.label_67.setText(_translate("MainWindow", "Level :", None))
        self.label_68.setText(_translate("MainWindow", "1", None))
        self.label_69.setText(_translate("MainWindow", "Stats :", None))
        self.comboBox_7.setItemText(0, _translate("MainWindow", "Best 3 of 5d6", None))
        self.comboBox_7.setItemText(1, _translate("MainWindow", "Low", None))
        self.comboBox_7.setItemText(2, _translate("MainWindow", "Average", None))
        self.comboBox_7.setItemText(3, _translate("MainWindow", "High", None))
        self.comboBox_7.setItemText(4, _translate("MainWindow", "Hero", None))
        self.create_campain_tabs.setTabText(self.create_campain_tabs.indexOf(self.npc_generator_tab), _translate("MainWindow", "NPC Generator", None))
        self.create_campain_tabs.setTabText(self.create_campain_tabs.indexOf(self.background_tab), _translate("MainWindow", "Background", None))
        self.actionNew_Campain.setText(_translate("MainWindow", "New Campain", None))
        self.actionSave_Campain.setText(_translate("MainWindow", "Save Campain", None))
        self.actionLoad_Campain.setText(_translate("MainWindow", "Load Campain", None))
        self.actionQuit.setText(_translate("MainWindow", "Quit", None))
        self.actionHost_Game.setText(_translate("MainWindow", "Host Game", None))
        self.actionConnect_to.setText(_translate("MainWindow", "Connect to...", None))
        self.actionHelp.setText(_translate("MainWindow", "Help", None))
        self.actionAbout.setText(_translate("MainWindow", "About", None))

import resources_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

